import {
  countWhere,
  currency,
  sum,
  type ResourceConfig,
  type Row,
} from "./resource";

const LIFECYCLE = ["in_use", "in_storage", "under_repair", "retired", "disposed", "lost"];
const CONDITION = ["excellent", "good", "fair", "poor", "damaged"];
const STATUS = ["active", "inactive"];
const PRIORITY = ["low", "medium", "high", "urgent"];
const WORK_STATUS = ["scheduled", "in_progress", "completed", "overdue", "cancelled"];

const isExpiring = (v: unknown, days = 30) => {
  if (!v) return false;
  const d = new Date(String(v)).getTime();
  const now = Date.now();
  return d >= now && d <= now + days * 86_400_000;
};
const isExpired = (v: unknown) => !!v && new Date(String(v)).getTime() < Date.now();

export const assetsConfig: ResourceConfig = {
  key: "assets",
  table: "assets",
  detailRoute: "/assets/$id",
  title: "Assets",
  singular: "Asset",
  description: "Full asset inventory with financials, lifecycle, location and technical detail.",
  icon: "Boxes",
  statusField: "lifecycle_status",
  statusOptions: LIFECYCLE,
  searchFields: ["name", "asset_tag", "serial_number", "manufacturer", "model", "assigned_user_name", "category_name"],
  columns: [
    { name: "asset_tag", label: "Tag", kind: "mono" },
    { name: "name", label: "Asset", className: "font-medium" },
    { name: "category_name", label: "Category" },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "serial_number", label: "Serial", kind: "mono" },
    { name: "lifecycle_status", label: "Lifecycle", kind: "badge" },
    { name: "condition", label: "Condition", kind: "badge" },
    { name: "assigned_user_name", label: "Assigned to" },
    { name: "building_name", label: "Building" },
    { name: "current_value", label: "Value", kind: "currency" },
    { name: "warranty_end", label: "Warranty ends", kind: "date" },
  ],
  kpis: (rows) => [
    { label: "Total assets", value: rows.length, icon: "Boxes" },
    { label: "Inventory value", value: currency(sum(rows, "current_value")), icon: "DollarSign", filter: { field: "current_value", op: "set" } },
    { label: "In use", value: countWhere(rows, (r) => r["lifecycle_status"] === "in_use"), icon: "CheckCircle2", tone: "success", filter: { field: "lifecycle_status", op: "eq", value: "in_use" } },
    {
      label: "Warranty expiring",
      value: countWhere(rows, (r) => isExpiring(r["warranty_end"])),
      icon: "ShieldAlert",
      tone: "warning",
      filter: { field: "warranty_end", op: "next_days", value: 30 },
    },
  ],
  fields: [
    { name: "name", label: "Asset name", required: true, group: "Basics" },
    { name: "asset_tag", label: "Asset tag", group: "Basics" },
    { name: "asset_type_id", label: "Asset type", group: "Basics", ref: { table: "asset_types", mirrorTo: "asset_type_name" }, help: "Define your own types under Asset Types." },
    { name: "category_id", label: "Category", group: "Basics", ref: { table: "asset_categories", mirrorTo: "category_name" } },
    { name: "asset_class", label: "Asset class", group: "Basics" },
    { name: "parent_asset_id", label: "Parent asset", group: "Basics", ref: { table: "assets", mirrorTo: "parent_asset_name" }, help: "Build component hierarchies, e.g. HVAC → compressor → motor." },
    { name: "manufacturer", label: "Manufacturer", group: "Basics" },
    { name: "model", label: "Model", group: "Basics" },
    { name: "serial_number", label: "Serial number", group: "Basics" },
    { name: "barcode", label: "Barcode", group: "Basics" },
    { name: "qr_code", label: "QR code value", group: "Basics" },
    { name: "criticality", label: "Criticality", type: "select", options: ["low", "medium", "high", "critical"], group: "Basics" },
    { name: "lifecycle_status", label: "Lifecycle status", type: "select", options: LIFECYCLE, group: "Basics" },
    { name: "condition", label: "Condition", type: "select", options: CONDITION, group: "Basics" },
    { name: "installation_date", label: "Installation date", type: "date", group: "Basics" },
    { name: "meter_reading", label: "Meter reading", type: "number", group: "Basics" },
    { name: "meter_unit", label: "Meter unit", group: "Basics", help: "km, hours, cycles…" },
    { name: "notes", label: "Notes", type: "textarea", group: "Basics" },

    { name: "photo_urls", label: "Asset photos", type: "files", accept: "image/*", folder: "asset-photos", group: "Files" },
    { name: "receipt_urls", label: "Receipt / purchase order", type: "files", accept: "image/*,application/pdf", folder: "asset-receipts", group: "Files" },
    { name: "document_urls", label: "Other documents", type: "files", folder: "asset-documents", group: "Files" },

    { name: "purchase_date", label: "Purchase date", type: "date", group: "Financial" },
    { name: "purchase_price", label: "Purchase price", type: "currency", group: "Financial" },
    { name: "current_value", label: "Current value", type: "currency", group: "Financial" },
    { name: "supplier", label: "Supplier", group: "Financial" },
    { name: "purchase_order_number", label: "PO number", group: "Financial" },
    { name: "invoice_number", label: "Invoice number", group: "Financial" },
    { name: "warranty_cost", label: "Warranty cost", type: "currency", group: "Financial" },
    { name: "tax_amount", label: "Tax amount", type: "currency", group: "Financial" },
    { name: "currency", label: "Currency", group: "Financial" },
    { name: "depreciation_method", label: "Depreciation method", type: "select", options: ["straight_line", "declining_balance", "none"], group: "Financial" },
    { name: "useful_life_years", label: "Useful life (years)", type: "number", group: "Financial" },
    { name: "residual_value", label: "Residual value", type: "currency", group: "Financial" },
    { name: "insurance_value", label: "Insurance value", type: "currency", group: "Financial" },
    { name: "replacement_cost", label: "Replacement cost", type: "currency", group: "Financial" },
    { name: "funding_source", label: "Funding source", group: "Financial" },
    { name: "cost_centre", label: "Cost centre", group: "Financial" },
    { name: "budget_code", label: "Budget code", group: "Financial" },

    { name: "vendor_id", label: "Vendor", ref: { table: "vendors", mirrorTo: "vendor_name" }, group: "Warranty" },
    { name: "warranty_start", label: "Warranty start", type: "date", group: "Warranty" },
    { name: "warranty_end", label: "Warranty end", type: "date", group: "Warranty" },
    { name: "next_maintenance_date", label: "Next maintenance", type: "date", group: "Warranty" },

    { name: "assigned_user_name", label: "Assigned to", group: "Location" },
    { name: "assigned_user_email", label: "Assignee email", type: "email", group: "Location" },
    { name: "department_id", label: "Department", ref: { table: "departments", mirrorTo: "department_name" }, group: "Location" },
    { name: "site_id", label: "Site", ref: { table: "sites", mirrorTo: "site_name" }, group: "Location" },
    { name: "building_id", label: "Building", ref: { table: "buildings", mirrorTo: "building_name" }, group: "Location" },
    { name: "room_id", label: "Room", ref: { table: "rooms", mirrorTo: "room_name" }, group: "Location" },
    { name: "gps_lat", label: "GPS latitude", type: "number", group: "Location" },
    { name: "gps_lng", label: "GPS longitude", type: "number", group: "Location" },

    { name: "hostname", label: "Hostname", group: "Technical" },
    { name: "ip_address", label: "IP address", group: "Technical" },
    { name: "mac_address", label: "MAC address", group: "Technical" },
    { name: "os", label: "Operating system", group: "Technical" },
    { name: "cpu", label: "CPU", group: "Technical" },
    { name: "ram_gb", label: "RAM (GB)", type: "number", group: "Technical" },
    { name: "disk_gb", label: "Disk (GB)", type: "number", group: "Technical" },
    { name: "online_status", label: "Online status", type: "select", options: ["online", "offline", "unknown"], group: "Technical" },
    { name: "logged_in_user", label: "Logged in user", group: "Technical" },
    { name: "installed_software", label: "Installed software", type: "textarea", group: "Technical" },
  ],
};

export const categoriesConfig: ResourceConfig = {
  key: "asset-categories",
  table: "asset_categories",
  title: "Asset Categories",
  singular: "Category",
  description: "Category tree, sector defaults, lifecycle years and depreciation methods.",
  icon: "FolderTree",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "sector", "description"],
  columns: [
    { name: "name", label: "Category", className: "font-medium" },
    { name: "sector", label: "Sector" },
    { name: "default_lifecycle_years", label: "Lifecycle (yrs)" },
    { name: "depreciation_method", label: "Depreciation" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Category name", required: true },
    { name: "icon", label: "Icon" },
    { name: "sector", label: "Sector" },
    { name: "parent_category_id", label: "Parent category", ref: { table: "asset_categories" } },
    { name: "default_lifecycle_years", label: "Default lifecycle (years)", type: "number" },
    { name: "depreciation_method", label: "Depreciation method", type: "select", options: ["straight_line", "declining_balance", "none"] },
    { name: "status", label: "Status", type: "select", options: STATUS },
    { name: "description", label: "Description", type: "textarea" },
  ],
};

export const vehiclesConfig: ResourceConfig = {
  key: "vehicles",
  table: "vehicles",
  title: "Vehicles",
  singular: "Vehicle",
  description: "Fleet register with drivers, telemetry, geofencing and service dates.",
  icon: "Truck",
  statusField: "status",
  statusOptions: ["active", "in_maintenance", "retired", "stolen"],
  searchFields: ["name", "license_plate", "make", "model", "vin", "driver_name"],
  columns: [
    { name: "name", label: "Vehicle", className: "font-medium" },
    { name: "license_plate", label: "Plate", kind: "mono" },
    { name: "make", label: "Make" },
    { name: "model", label: "Model" },
    { name: "year", label: "Year" },
    { name: "vehicle_type", label: "Type", kind: "badge" },
    { name: "driver_name", label: "Driver" },
    { name: "total_mileage_km", label: "Odometer (km)" },
    { name: "fuel_level_pct", label: "Fuel", kind: "pct" },
    { name: "geofence_breach", label: "Breach", kind: "bool" },
    { name: "next_service_date", label: "Next service", kind: "date" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Fleet size", value: rows.length, icon: "Truck" },
    { label: "Active", value: countWhere(rows, (r) => r["status"] === "active"), icon: "CheckCircle2", tone: "success", filter: { field: "status", op: "eq", value: "active" } },
    { label: "Geofence breaches", value: countWhere(rows, (r) => !!r["geofence_breach"]), icon: "AlertTriangle", tone: "destructive", filter: { field: "geofence_breach", op: "truthy" } },
    { label: "Service due (30d)", value: countWhere(rows, (r) => isExpiring(r["next_service_date"])), icon: "Wrench", tone: "warning", filter: { field: "next_service_date", op: "next_days", value: 30 } },
  ],
  fields: [
    { name: "name", label: "Vehicle name", required: true, group: "Vehicle" },
    { name: "license_plate", label: "License plate", group: "Vehicle" },
    { name: "make", label: "Make", group: "Vehicle" },
    { name: "model", label: "Model", group: "Vehicle" },
    { name: "year", label: "Year", type: "number", group: "Vehicle" },
    { name: "vin", label: "VIN", group: "Vehicle" },
    { name: "vehicle_type", label: "Vehicle type", type: "select", options: ["car", "van", "truck", "suv", "motorcycle", "heavy_equipment", "other"], group: "Vehicle" },
    { name: "color", label: "Colour", group: "Vehicle" },
    { name: "status", label: "Status", type: "select", options: ["active", "in_maintenance", "retired", "stolen"], group: "Vehicle" },
    { name: "notes", label: "Notes", type: "textarea", group: "Vehicle" },

    { name: "driver_name", label: "Driver", group: "Driver" },
    { name: "driver_email", label: "Driver email", type: "email", group: "Driver" },
    { name: "driver_phone", label: "Driver phone", group: "Driver" },

    { name: "gps_lat", label: "GPS latitude", type: "number", group: "Telemetry" },
    { name: "gps_lng", label: "GPS longitude", type: "number", group: "Telemetry" },
    { name: "current_speed_kmh", label: "Current speed (km/h)", type: "number", group: "Telemetry" },
    { name: "daily_mileage_km", label: "Daily mileage (km)", type: "number", group: "Telemetry" },
    { name: "total_mileage_km", label: "Total mileage (km)", type: "number", group: "Telemetry" },
    { name: "fuel_level_pct", label: "Fuel level (%)", type: "number", group: "Telemetry" },
    { name: "geofence_id", label: "Geofence", ref: { table: "geofences", mirrorTo: "geofence_name" }, group: "Telemetry" },
    { name: "geofence_breach", label: "Geofence breach", type: "switch", group: "Telemetry" },

    { name: "purchase_date", label: "Purchase date", type: "date", group: "Compliance" },
    { name: "purchase_price", label: "Purchase price", type: "currency", group: "Compliance" },
    { name: "insurance_expiry", label: "Insurance expiry", type: "date", group: "Compliance" },
    { name: "registration_expiry", label: "Registration expiry", type: "date", group: "Compliance" },
    { name: "last_service_date", label: "Last service", type: "date", group: "Compliance" },
    { name: "next_service_date", label: "Next service", type: "date", group: "Compliance" },
    { name: "tire_rotation_date", label: "Tire rotation", type: "date", group: "Compliance" },
    { name: "winter_tires_installed", label: "Winter tires installed", type: "switch", group: "Compliance" },
    { name: "summer_tires_installed", label: "Summer tires installed", type: "switch", group: "Compliance" },
  ],
};

export const vehicleServiceConfig: ResourceConfig = {
  key: "vehicle-service",
  table: "vehicle_service_records",
  title: "Vehicle Service Records",
  singular: "Service Record",
  description: "Servicing, tire changes and repairs logged per vehicle.",
  icon: "Wrench",
  statusField: "status",
  statusOptions: WORK_STATUS,
  searchFields: ["title", "vehicle_name", "service_type", "technician_name"],
  columns: [
    { name: "title", label: "Service", className: "font-medium" },
    { name: "vehicle_name", label: "Vehicle" },
    { name: "service_type", label: "Type", kind: "badge" },
    { name: "scheduled_date", label: "Scheduled", kind: "date" },
    { name: "completed_date", label: "Completed", kind: "date" },
    { name: "odometer_km", label: "Odometer" },
    { name: "cost", label: "Cost", kind: "currency" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "vehicle_id", label: "Vehicle", required: true, ref: { table: "vehicles", mirrorTo: "vehicle_name" } },
    { name: "title", label: "Title", required: true },
    { name: "service_type", label: "Service type", type: "select", options: ["preventive", "repair", "inspection", "tire_change", "oil_change", "other"] },
    { name: "status", label: "Status", type: "select", options: WORK_STATUS },
    { name: "scheduled_date", label: "Scheduled date", type: "date" },
    { name: "completed_date", label: "Completed date", type: "date" },
    { name: "technician_name", label: "Technician" },
    { name: "cost", label: "Cost", type: "currency" },
    { name: "odometer_km", label: "Odometer (km)", type: "number" },
    { name: "tire_season", label: "Tire season", type: "select", options: ["winter", "summer", "all_season"] },
    { name: "parts_used", label: "Parts used" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const maintenanceConfig: ResourceConfig = {
  key: "maintenance",
  table: "maintenance_records",
  title: "Maintenance",
  singular: "Work Order",
  description: "Preventive and corrective maintenance across every asset.",
  icon: "Wrench",
  statusField: "status",
  statusOptions: WORK_STATUS,
  searchFields: ["title", "asset_name", "technician_name", "vendor_name", "maintenance_type"],
  columns: [
    { name: "title", label: "Work order", className: "font-medium" },
    { name: "asset_name", label: "Asset" },
    { name: "maintenance_type", label: "Type", kind: "badge" },
    { name: "priority", label: "Priority", kind: "badge" },
    { name: "scheduled_date", label: "Scheduled", kind: "date" },
    { name: "completed_date", label: "Completed", kind: "date" },
    { name: "technician_name", label: "Technician" },
    { name: "cost", label: "Cost", kind: "currency" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Open work orders", value: countWhere(rows, (r) => r["status"] !== "completed" && r["status"] !== "cancelled"), icon: "Wrench", filter: { field: "status", op: "nin", value: ["completed", "cancelled"] } },
    { label: "Overdue", value: countWhere(rows, (r) => r["status"] !== "completed" && isExpired(r["scheduled_date"])), icon: "AlertTriangle", tone: "destructive", filter: [{ field: "status", op: "nin", value: ["completed", "cancelled"] }, { field: "scheduled_date", op: "past" }] },
    { label: "Completed", value: countWhere(rows, (r) => r["status"] === "completed"), icon: "CheckCircle2", tone: "success", filter: { field: "status", op: "eq", value: "completed" } },
    { label: "Total spend", value: currency(sum(rows, "cost")), icon: "DollarSign", filter: { field: "cost", op: "gt", value: 0 } },
  ],
  fields: [
    { name: "title", label: "Title", required: true },
    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" } },
    { name: "maintenance_type", label: "Maintenance type", type: "select", options: ["preventive", "corrective", "inspection", "calibration", "upgrade"] },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY },
    { name: "status", label: "Status", type: "select", options: WORK_STATUS },
    { name: "scheduled_date", label: "Scheduled date", type: "date" },
    { name: "completed_date", label: "Completed date", type: "date" },
    { name: "technician_name", label: "Technician" },
    { name: "vendor_id", label: "Vendor", ref: { table: "vendors", mirrorTo: "vendor_name" } },
    { name: "cost", label: "Cost", type: "currency" },
    { name: "parts_used", label: "Parts used" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const softwareConfig: ResourceConfig = {
  key: "software",
  table: "software_licenses",
  title: "Software Licences",
  singular: "Licence",
  description: "Licence inventory, seat usage, renewals and compliance posture.",
  icon: "AppWindow",
  statusField: "compliance_status",
  statusOptions: ["compliant", "at_risk", "non_compliant"],
  searchFields: ["software_name", "publisher", "license_type", "vendor_name"],
  columns: [
    { name: "software_name", label: "Software", className: "font-medium" },
    { name: "publisher", label: "Publisher" },
    { name: "version", label: "Version" },
    { name: "license_type", label: "Type", kind: "badge" },
    {
      name: "seats",
      label: "Seats",
      render: (r: Row) => `${Number(r["used_seats"] ?? 0)} / ${Number(r["total_seats"] ?? 0)}`,
    },
    { name: "expiration_date", label: "Expires", kind: "date" },
    { name: "total_cost", label: "Total cost", kind: "currency" },
    { name: "compliance_status", label: "Compliance", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Licences", value: rows.length, icon: "AppWindow" },
    { label: "Seats in use", value: sum(rows, "used_seats"), icon: "Users", filter: { field: "used_seats", op: "gt", value: 0 } },
    { label: "Expiring (30d)", value: countWhere(rows, (r) => isExpiring(r["expiration_date"])), icon: "CalendarClock", tone: "warning", filter: { field: "expiration_date", op: "next_days", value: 30 } },
    { label: "Annual spend", value: currency(sum(rows, "total_cost")), icon: "DollarSign", filter: { field: "total_cost", op: "gt", value: 0 } },
  ],
  fields: [
    { name: "software_name", label: "Software name", required: true },
    { name: "publisher", label: "Publisher" },
    { name: "version", label: "Version" },
    { name: "license_key", label: "Licence key" },
    { name: "license_type", label: "Licence type", type: "select", options: ["perpetual", "subscription", "open_source", "volume", "oem"] },
    { name: "total_seats", label: "Total seats", type: "number" },
    { name: "used_seats", label: "Used seats", type: "number" },
    { name: "purchase_date", label: "Purchase date", type: "date" },
    { name: "expiration_date", label: "Expiration date", type: "date" },
    { name: "cost_per_seat", label: "Cost per seat", type: "currency" },
    { name: "total_cost", label: "Total cost", type: "currency" },
    { name: "vendor_id", label: "Vendor", ref: { table: "vendors", mirrorTo: "vendor_name" } },
    { name: "compliance_status", label: "Compliance status", type: "select", options: ["compliant", "at_risk", "non_compliant"] },
    { name: "status", label: "Status", type: "select", options: STATUS },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const vendorsConfig: ResourceConfig = {
  key: "vendors",
  table: "vendors",
  title: "Vendors",
  singular: "Vendor",
  description: "Suppliers, service partners and their contract windows.",
  icon: "Handshake",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "contact_name", "email", "vendor_type", "contract_number"],
  columns: [
    { name: "name", label: "Vendor", className: "font-medium" },
    { name: "vendor_type", label: "Type", kind: "badge" },
    { name: "contact_name", label: "Contact" },
    { name: "email", label: "Email" },
    { name: "phone", label: "Phone" },
    { name: "contract_end", label: "Contract ends", kind: "date" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Vendor name", required: true },
    { name: "vendor_type", label: "Vendor type", type: "select", options: ["supplier", "service", "reseller", "manufacturer", "consultant"] },
    { name: "contact_name", label: "Contact name" },
    { name: "email", label: "Email", type: "email" },
    { name: "phone", label: "Phone" },
    { name: "website", label: "Website" },
    { name: "address", label: "Address" },
    { name: "contract_number", label: "Contract number" },
    { name: "contract_start", label: "Contract start", type: "date" },
    { name: "contract_end", label: "Contract end", type: "date" },
    { name: "status", label: "Status", type: "select", options: STATUS },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const departmentsConfig: ResourceConfig = {
  key: "departments",
  table: "departments",
  title: "Departments",
  singular: "Department",
  description: "Departments, cost centres and reporting lines.",
  icon: "Building2",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "head_name", "cost_center"],
  columns: [
    { name: "name", label: "Department", className: "font-medium" },
    { name: "head_name", label: "Head" },
    { name: "head_email", label: "Head email" },
    { name: "cost_center", label: "Cost centre" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Department name", required: true },
    { name: "head_name", label: "Department head" },
    { name: "head_email", label: "Head email", type: "email" },
    { name: "parent_department_id", label: "Parent department", ref: { table: "departments" } },
    { name: "cost_center", label: "Cost centre" },
    { name: "status", label: "Status", type: "select", options: STATUS },
  ],
};

export const buildingsConfig: ResourceConfig = {
  key: "buildings",
  table: "buildings",
  title: "Buildings",
  singular: "Building",
  description: "Sites and buildings that hold your assets.",
  icon: "Building",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "city", "address", "country"],
  columns: [
    { name: "name", label: "Building", className: "font-medium" },
    { name: "address", label: "Address" },
    { name: "city", label: "City" },
    { name: "state", label: "Province / State" },
    { name: "country", label: "Country" },
    { name: "floors", label: "Floors" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Building name", required: true },
    { name: "address", label: "Address" },
    { name: "city", label: "City" },
    { name: "state", label: "Province / State" },
    { name: "zip_code", label: "Postal code" },
    { name: "country", label: "Country" },
    { name: "floors", label: "Number of floors", type: "number" },
    { name: "status", label: "Status", type: "select", options: STATUS },
  ],
};

export const roomsConfig: ResourceConfig = {
  key: "rooms",
  table: "rooms",
  title: "Rooms",
  singular: "Room",
  description: "Rooms and floors inside each building.",
  icon: "DoorOpen",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "room_number", "floor", "room_type"],
  columns: [
    { name: "name", label: "Room", className: "font-medium" },
    { name: "room_number", label: "Number" },
    { name: "floor", label: "Floor" },
    { name: "room_type", label: "Type" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Room name", required: true },
    { name: "building_id", label: "Building", ref: { table: "buildings" } },
    { name: "room_number", label: "Room number" },
    { name: "floor", label: "Floor" },
    { name: "room_type", label: "Room type" },
    { name: "status", label: "Status", type: "select", options: STATUS },
  ],
};

export const assignmentsConfig: ResourceConfig = {
  key: "assignments",
  table: "asset_assignments",
  title: "Assignments",
  singular: "Assignment",
  description: "Who holds which asset, and its assignment history.",
  icon: "UserCheck",
  statusField: "status",
  statusOptions: ["active", "returned", "overdue"],
  searchFields: ["asset_name", "assigned_to_name", "assigned_to_email", "assigned_by_name"],
  columns: [
    { name: "asset_name", label: "Asset", className: "font-medium" },
    { name: "assigned_to_name", label: "Assigned to" },
    { name: "assigned_to_email", label: "Email" },
    { name: "assignment_date", label: "Assigned", kind: "date" },
    { name: "return_date", label: "Returned", kind: "date" },
    { name: "previous_owner_name", label: "Previous owner" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" } },
    { name: "assigned_to_name", label: "Assigned to", required: true },
    { name: "assigned_to_email", label: "Assignee email", type: "email" },
    { name: "assigned_by_name", label: "Assigned by" },
    { name: "assignment_date", label: "Assignment date", type: "date" },
    { name: "return_date", label: "Return date", type: "date" },
    { name: "previous_owner_name", label: "Previous owner" },
    { name: "status", label: "Status", type: "select", options: ["active", "returned", "overdue"] },
    { name: "reason", label: "Reason" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const distributionConfig: ResourceConfig = {
  key: "distribution",
  table: "distribution_requests",
  title: "Distribution",
  singular: "Request",
  description: "Equipment requests, approvals and fulfilment.",
  icon: "PackageCheck",
  statusField: "status",
  statusOptions: ["pending", "approved", "fulfilled", "rejected", "returned"],
  searchFields: ["asset_name", "requested_by_name", "assigned_to_name", "department"],
  columns: [
    { name: "asset_name", label: "Item", className: "font-medium" },
    { name: "asset_category", label: "Category" },
    { name: "requested_by_name", label: "Requested by" },
    { name: "assigned_to_name", label: "For" },
    { name: "department", label: "Department" },
    { name: "priority", label: "Priority", kind: "badge" },
    { name: "request_date", label: "Requested", kind: "date" },
    { name: "fulfilled_date", label: "Fulfilled", kind: "date" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Pending", value: countWhere(rows, (r) => r["status"] === "pending"), icon: "Clock", tone: "warning", filter: { field: "status", op: "eq", value: "pending" } },
    { label: "Approved", value: countWhere(rows, (r) => r["status"] === "approved"), icon: "CheckCircle2", tone: "success", filter: { field: "status", op: "eq", value: "approved" } },
    { label: "Fulfilled", value: countWhere(rows, (r) => r["status"] === "fulfilled"), icon: "PackageCheck", filter: { field: "status", op: "eq", value: "fulfilled" } },
    { label: "Urgent", value: countWhere(rows, (r) => r["priority"] === "urgent"), icon: "AlertTriangle", tone: "destructive", filter: { field: "priority", op: "eq", value: "urgent" } },
  ],
  fields: [
    { name: "asset_name", label: "Item requested", required: true },
    { name: "asset_id", label: "Existing asset", ref: { table: "assets" } },
    { name: "asset_category", label: "Category" },
    { name: "requested_by_name", label: "Requested by" },
    { name: "requested_by_email", label: "Requester email", type: "email" },
    { name: "assigned_to_name", label: "Assign to", required: true },
    { name: "assigned_to_email", label: "Assignee email", type: "email" },
    { name: "department", label: "Department" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY },
    { name: "status", label: "Status", type: "select", options: ["pending", "approved", "fulfilled", "rejected", "returned"] },
    { name: "request_date", label: "Request date", type: "date" },
    { name: "fulfilled_date", label: "Fulfilled date", type: "date" },
    { name: "return_date", label: "Return date", type: "date" },
    { name: "item_condition", label: "Condition", type: "select", options: CONDITION },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const networkConfig: ResourceConfig = {
  key: "network",
  table: "network_devices",
  title: "Network Discovery",
  singular: "Device",
  description: "Discovered endpoints, their hardware profile and live connectivity.",
  icon: "Network",
  statusField: "online_status",
  statusOptions: ["online", "offline", "unknown"],
  searchFields: ["hostname", "ip_address", "mac_address", "manufacturer", "logged_in_user", "device_type"],
  columns: [
    { name: "hostname", label: "Hostname", className: "font-medium" },
    { name: "ip_address", label: "IP", kind: "mono" },
    { name: "mac_address", label: "MAC", kind: "mono" },
    { name: "device_type", label: "Type", kind: "badge" },
    { name: "os", label: "OS" },
    { name: "logged_in_user", label: "User" },
    { name: "building", label: "Building" },
    { name: "vlan", label: "VLAN" },
    { name: "signal_strength", label: "Signal" },
    { name: "last_seen", label: "Last seen", kind: "datetime" },
    { name: "online_status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Discovered devices", value: rows.length, icon: "Network" },
    { label: "Online", value: countWhere(rows, (r) => r["online_status"] === "online"), icon: "Wifi", tone: "success", filter: { field: "online_status", op: "eq", value: "online" } },
    { label: "Offline", value: countWhere(rows, (r) => r["online_status"] === "offline"), icon: "WifiOff", tone: "destructive", filter: { field: "online_status", op: "eq", value: "offline" } },
    { label: "Unlinked", value: countWhere(rows, (r) => !r["linked_asset_id"]), icon: "Unlink", tone: "warning", filter: { field: "linked_asset_id", op: "unset" } },
  ],
  fields: [
    { name: "hostname", label: "Hostname", group: "Device" },
    { name: "ip_address", label: "IP address", group: "Device" },
    { name: "mac_address", label: "MAC address", group: "Device" },
    { name: "manufacturer", label: "Manufacturer", group: "Device" },
    { name: "device_type", label: "Device type", type: "select", options: ["workstation", "laptop", "server", "printer", "phone", "iot", "network", "other"], group: "Device" },
    { name: "os", label: "Operating system", group: "Device" },
    { name: "cpu", label: "CPU", group: "Device" },
    { name: "ram_gb", label: "RAM (GB)", type: "number", group: "Device" },
    { name: "disk_gb", label: "Disk (GB)", type: "number", group: "Device" },
    { name: "disk_used_pct", label: "Disk used (%)", type: "number", group: "Device" },
    { name: "logged_in_user", label: "Logged in user", group: "Device" },
    { name: "antivirus_status", label: "Antivirus status", group: "Device" },
    { name: "installed_software", label: "Installed software", type: "textarea", group: "Device" },

    { name: "online_status", label: "Online status", type: "select", options: ["online", "offline", "unknown"], group: "Network" },
    { name: "connection_type", label: "Connection type", type: "select", options: ["wired", "wireless"], group: "Network" },
    { name: "network_name", label: "Network name", group: "Network" },
    { name: "ssid", label: "SSID", group: "Network" },
    { name: "vlan", label: "VLAN", group: "Network" },
    { name: "switch_port", label: "Switch port", group: "Network" },
    { name: "access_point", label: "Access point", group: "Network" },
    { name: "access_point_location", label: "AP location", group: "Network" },
    { name: "signal_strength", label: "Signal strength", type: "number", group: "Network" },
    { name: "ping_time_ms", label: "Ping (ms)", type: "number", group: "Network" },
    { name: "discovery_source", label: "Discovery source", group: "Network" },

    { name: "building", label: "Building", group: "Location" },
    { name: "floor", label: "Floor", group: "Location" },
    { name: "room", label: "Room", group: "Location" },
    { name: "linked_asset_id", label: "Linked asset", ref: { table: "assets" }, group: "Location" },
    { name: "status", label: "Record status", type: "select", options: STATUS, group: "Location" },
  ],
};

export const geofencesConfig: ResourceConfig = {
  key: "geofences",
  table: "geofences",
  title: "Geofences",
  singular: "Geofence",
  description: "Virtual perimeters with entry/exit alerting for the fleet.",
  icon: "MapPinned",
  searchFields: ["name", "description"],
  columns: [
    { name: "name", label: "Geofence", className: "font-medium" },
    { name: "center_lat", label: "Latitude" },
    { name: "center_lng", label: "Longitude" },
    { name: "radius_meters", label: "Radius (m)" },
    { name: "speed_limit_kmh", label: "Speed limit" },
    { name: "alert_on_entry", label: "Alert entry", kind: "bool" },
    { name: "alert_on_exit", label: "Alert exit", kind: "bool" },
    { name: "active", label: "Active", kind: "bool" },
  ],
  fields: [
    { name: "name", label: "Geofence name", required: true },
    { name: "center_lat", label: "Centre latitude", type: "number", required: true },
    { name: "center_lng", label: "Centre longitude", type: "number", required: true },
    { name: "radius_meters", label: "Radius (metres)", type: "number", required: true },
    { name: "speed_limit_kmh", label: "Speed limit (km/h)", type: "number" },
    { name: "color", label: "Colour" },
    { name: "alert_on_entry", label: "Alert on entry", type: "switch" },
    { name: "alert_on_exit", label: "Alert on exit", type: "switch" },
    { name: "active", label: "Active", type: "switch" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const rfidTagsConfig: ResourceConfig = {
  key: "rfid-assets",
  table: "rfid_tags",
  title: "Tagged Assets",
  singular: "Tag",
  description: "RFID tags bonded to assets, with battery and last-seen telemetry.",
  icon: "Tags",
  statusField: "tag_status",
  statusOptions: ["active", "inactive", "lost", "damaged"],
  searchFields: ["tag_id", "asset_name", "manufacturer", "last_detected_zone"],
  columns: [
    { name: "tag_id", label: "Tag ID", kind: "mono" },
    { name: "asset_name", label: "Asset", className: "font-medium" },
    { name: "rfid_type", label: "Type", kind: "badge" },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "battery_level_pct", label: "Battery", kind: "pct" },
    { name: "last_detected_zone", label: "Last zone" },
    { name: "last_detection_time", label: "Last seen", kind: "datetime" },
    { name: "tag_status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Tags", value: rows.length, icon: "Tags" },
    { label: "Active", value: countWhere(rows, (r) => r["tag_status"] === "active"), icon: "CheckCircle2", tone: "success", filter: { field: "tag_status", op: "eq", value: "active" } },
    { label: "Low battery", value: countWhere(rows, (r) => Number(r["battery_level_pct"] ?? 100) < 20), icon: "BatteryLow", tone: "warning", filter: { field: "battery_level_pct", op: "lt", value: 20 } },
    { label: "Lost / damaged", value: countWhere(rows, (r) => r["tag_status"] === "lost" || r["tag_status"] === "damaged"), icon: "AlertTriangle", tone: "destructive", filter: { field: "tag_status", op: "in", value: ["lost", "damaged"] } },
  ],
  fields: [
    { name: "tag_id", label: "Tag ID", required: true },
    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" } },
    { name: "rfid_type", label: "RFID type", type: "select", options: ["passive", "active", "ble", "uhf", "nfc"] },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "tag_status", label: "Tag status", type: "select", options: ["active", "inactive", "lost", "damaged"] },
    { name: "installation_date", label: "Installation date", type: "date" },
    { name: "battery_status", label: "Battery status", type: "select", options: ["good", "low", "critical", "n_a"] },
    { name: "battery_level_pct", label: "Battery level (%)", type: "number" },
    { name: "last_detected_zone", label: "Last detected zone" },
    { name: "last_detected_reader", label: "Last detected reader" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const rfidReadersConfig: ResourceConfig = {
  key: "rfid-readers",
  table: "rfid_readers",
  title: "RFID Readers",
  singular: "Reader",
  description: "Fixed and handheld readers, their health and heartbeat.",
  icon: "ScanLine",
  statusField: "reader_status",
  statusOptions: ["online", "offline", "maintenance"],
  searchFields: ["name", "reader_id", "ip_address", "building_name", "zone_name"],
  columns: [
    { name: "name", label: "Reader", className: "font-medium" },
    { name: "reader_id", label: "Reader ID", kind: "mono" },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "ip_address", label: "IP", kind: "mono" },
    { name: "building_name", label: "Building" },
    { name: "zone_name", label: "Zone" },
    { name: "antenna_count", label: "Antennas" },
    { name: "reader_health", label: "Health", kind: "badge" },
    { name: "last_heartbeat", label: "Heartbeat", kind: "datetime" },
    { name: "reader_status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Readers", value: rows.length, icon: "ScanLine" },
    { label: "Online", value: countWhere(rows, (r) => r["reader_status"] === "online"), icon: "Wifi", tone: "success", filter: { field: "reader_status", op: "eq", value: "online" } },
    { label: "Offline", value: countWhere(rows, (r) => r["reader_status"] === "offline"), icon: "WifiOff", tone: "destructive", filter: { field: "reader_status", op: "eq", value: "offline" } },
    { label: "Needs attention", value: countWhere(rows, (r) => r["reader_health"] === "critical" || r["reader_health"] === "degraded"), icon: "AlertTriangle", tone: "warning", filter: { field: "reader_health", op: "in", value: ["critical", "degraded"] } },
  ],
  fields: [
    { name: "name", label: "Reader name", required: true, group: "Reader" },
    { name: "reader_id", label: "Reader ID", group: "Reader" },
    { name: "manufacturer", label: "Manufacturer", group: "Reader" },
    { name: "model", label: "Model", group: "Reader" },
    { name: "firmware_version", label: "Firmware version", group: "Reader" },
    { name: "provider_type", label: "Provider type", group: "Reader" },
    { name: "antenna_count", label: "Antenna count", type: "number", group: "Reader" },
    { name: "read_range_meters", label: "Read range (m)", type: "number", group: "Reader" },
    { name: "reader_status", label: "Reader status", type: "select", options: ["online", "offline", "maintenance"], group: "Reader" },
    { name: "reader_health", label: "Reader health", type: "select", options: ["healthy", "degraded", "critical"], group: "Reader" },
    { name: "notes", label: "Notes", type: "textarea", group: "Reader" },

    { name: "ip_address", label: "IP address", group: "Placement" },
    { name: "mac_address", label: "MAC address", group: "Placement" },
    { name: "building_id", label: "Building", ref: { table: "buildings", mirrorTo: "building_name" }, group: "Placement" },
    { name: "floor", label: "Floor", group: "Placement" },
    { name: "room", label: "Room", group: "Placement" },
    { name: "zone_id", label: "Zone", ref: { table: "rfid_zones", mirrorTo: "zone_name" }, group: "Placement" },
    { name: "gateway_id", label: "Gateway", ref: { table: "rfid_gateways", mirrorTo: "gateway_name" }, group: "Placement" },
  ],
};

export const rfidZonesConfig: ResourceConfig = {
  key: "rfid-zones",
  table: "rfid_zones",
  title: "RFID Zones",
  singular: "Zone",
  description: "Logical zones that group readers and control restricted areas.",
  icon: "LayoutGrid",
  statusField: "zone_type",
  statusOptions: ["storage", "office", "entrance", "exit", "restricted", "workshop", "outdoor"],
  searchFields: ["name", "building_name", "floor", "room", "description"],
  columns: [
    { name: "name", label: "Zone", className: "font-medium" },
    { name: "building_name", label: "Building" },
    { name: "floor", label: "Floor" },
    { name: "room", label: "Room" },
    { name: "zone_type", label: "Type", kind: "badge" },
    { name: "restricted", label: "Restricted", kind: "bool" },
    { name: "authorized_only", label: "Authorised only", kind: "bool" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Zone name", required: true },
    { name: "building_id", label: "Building", ref: { table: "buildings", mirrorTo: "building_name" } },
    { name: "floor", label: "Floor" },
    { name: "room", label: "Room" },
    { name: "zone_type", label: "Zone type", type: "select", options: ["storage", "office", "entrance", "exit", "restricted", "workshop", "outdoor"] },
    { name: "restricted", label: "Restricted", type: "switch" },
    { name: "authorized_only", label: "Authorised personnel only", type: "switch" },
    { name: "color", label: "Colour" },
    { name: "status", label: "Status", type: "select", options: STATUS },
    { name: "description", label: "Description", type: "textarea" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const rfidGatewaysConfig: ResourceConfig = {
  key: "rfid-gateways",
  table: "rfid_gateways",
  title: "RFID Gateways",
  singular: "Gateway",
  description: "Edge gateways aggregating reader traffic per site.",
  icon: "Router",
  statusField: "gateway_status",
  statusOptions: ["online", "offline", "maintenance"],
  searchFields: ["name", "gateway_id", "ip_address", "building_name"],
  columns: [
    { name: "name", label: "Gateway", className: "font-medium" },
    { name: "gateway_id", label: "Gateway ID", kind: "mono" },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "ip_address", label: "IP", kind: "mono" },
    { name: "building_name", label: "Building" },
    { name: "connected_reader_count", label: "Readers" },
    { name: "last_heartbeat", label: "Heartbeat", kind: "datetime" },
    { name: "gateway_status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "name", label: "Gateway name", required: true },
    { name: "gateway_id", label: "Gateway ID" },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "model", label: "Model" },
    { name: "firmware_version", label: "Firmware version" },
    { name: "ip_address", label: "IP address" },
    { name: "mac_address", label: "MAC address" },
    { name: "building_name", label: "Building" },
    { name: "floor", label: "Floor" },
    { name: "gateway_status", label: "Gateway status", type: "select", options: ["online", "offline", "maintenance"] },
    { name: "connected_reader_count", label: "Connected readers", type: "number" },
    { name: "provider_type", label: "Provider type" },
    { name: "status", label: "Record status", type: "select", options: STATUS },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const rfidAlertsConfig: ResourceConfig = {
  key: "rfid-alerts",
  table: "rfid_alerts",
  title: "RFID Alerts",
  singular: "Alert",
  description: "Unauthorised movement, zone breaches and tag health alerts.",
  icon: "BellRing",
  statusField: "severity",
  statusOptions: ["low", "medium", "high", "critical"],
  orderBy: { column: "detected_at", ascending: false },
  searchFields: ["message", "asset_name", "zone_name", "reader_name", "alert_type"],
  columns: [
    { name: "detected_at", label: "Detected", kind: "datetime" },
    { name: "alert_type", label: "Type", kind: "badge" },
    { name: "severity", label: "Severity", kind: "badge" },
    { name: "message", label: "Message", className: "max-w-[380px] truncate whitespace-normal" },
    { name: "asset_name", label: "Asset" },
    { name: "zone_name", label: "Zone" },
    { name: "reader_name", label: "Reader" },
    { name: "acknowledged", label: "Acknowledged", kind: "bool" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Open alerts", value: countWhere(rows, (r) => r["status"] === "active"), icon: "BellRing", tone: "warning", filter: { field: "status", op: "eq", value: "active" } },
    { label: "Critical", value: countWhere(rows, (r) => r["severity"] === "critical"), icon: "AlertTriangle", tone: "destructive", filter: { field: "severity", op: "eq", value: "critical" } },
    { label: "Unacknowledged", value: countWhere(rows, (r) => !r["acknowledged"]), icon: "EyeOff", filter: { field: "acknowledged", op: "falsy" } },
    { label: "Total", value: rows.length, icon: "ListChecks" },
  ],
  fields: [
    { name: "message", label: "Message", required: true, type: "textarea" },
    { name: "alert_type", label: "Alert type", type: "select", options: ["unauthorized_movement", "zone_breach", "tag_offline", "low_battery", "asset_missing", "restricted_entry"] },
    { name: "severity", label: "Severity", type: "select", options: ["low", "medium", "high", "critical"] },
    { name: "tag_id", label: "Tag ID" },
    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" } },
    { name: "reader_name", label: "Reader" },
    { name: "zone_name", label: "Zone" },
    { name: "building_name", label: "Building" },
    { name: "detected_at", label: "Detected at", type: "datetime" },
    { name: "acknowledged", label: "Acknowledged", type: "switch" },
    { name: "acknowledged_by", label: "Acknowledged by" },
    { name: "status", label: "Status", type: "select", options: ["active", "resolved", "dismissed"] },
  ],
};

export const rfidDetectionsConfig: ResourceConfig = {
  key: "rfid-movement",
  table: "rfid_detections",
  title: "Movement History",
  singular: "Detection",
  description: "Every tag read, with direction of travel and zone transitions.",
  icon: "History",
  statusField: "movement_status",
  statusOptions: ["normal", "suspicious", "unauthorized"],
  orderBy: { column: "detection_time", ascending: false },
  searchFields: ["tag_id", "asset_name", "zone_name", "reader_name", "assigned_user"],
  columns: [
    { name: "detection_time", label: "Time", kind: "datetime" },
    { name: "tag_id", label: "Tag", kind: "mono" },
    { name: "asset_name", label: "Asset", className: "font-medium" },
    { name: "direction", label: "Direction", kind: "badge" },
    { name: "previous_zone", label: "From" },
    { name: "zone_name", label: "To" },
    { name: "reader_name", label: "Reader" },
    { name: "signal_strength", label: "Signal" },
    { name: "movement_status", label: "Movement", kind: "badge" },
  ],
  fields: [
    { name: "tag_id", label: "Tag ID", required: true },
    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" } },
    { name: "zone_id", label: "Zone", ref: { table: "rfid_zones", mirrorTo: "zone_name" } },
    { name: "reader_name", label: "Reader" },
    { name: "building_name", label: "Building" },
    { name: "floor", label: "Floor" },
    { name: "detection_time", label: "Detection time", type: "datetime" },
    { name: "direction", label: "Direction", type: "select", options: ["in", "out", "stationary"] },
    { name: "signal_strength", label: "Signal strength", type: "number" },
    { name: "previous_zone", label: "Previous zone" },
    { name: "previous_reader", label: "Previous reader" },
    { name: "assigned_user", label: "Assigned user" },
    { name: "technician", label: "Technician" },
    { name: "movement_status", label: "Movement status", type: "select", options: ["normal", "suspicious", "unauthorized"] },
  ],
};

export const rfidOnboardingConfig: ResourceConfig = {
  key: "rfid-onboarding",
  table: "rfid_deployment_requests",
  title: "RFID Onboarding",
  singular: "Deployment Request",
  description: "Requests to roll out RFID hardware across sites.",
  icon: "Rocket",
  statusField: "request_status",
  statusOptions: ["new", "in_review", "scheduled", "in_progress", "completed", "rejected"],
  searchFields: ["company_name", "contact_person", "email", "industry"],
  columns: [
    { name: "company_name", label: "Company", className: "font-medium" },
    { name: "contact_person", label: "Contact" },
    { name: "email", label: "Email" },
    { name: "number_of_buildings", label: "Buildings" },
    { name: "estimated_assets", label: "Est. assets" },
    { name: "industry", label: "Industry" },
    { name: "preferred_installation_date", label: "Preferred date", kind: "date" },
    { name: "request_status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "company_name", label: "Company name", required: true },
    { name: "contact_person", label: "Contact person", required: true },
    { name: "email", label: "Email", type: "email", required: true },
    { name: "phone", label: "Phone" },
    { name: "number_of_buildings", label: "Number of buildings", type: "number" },
    { name: "estimated_assets", label: "Estimated assets", type: "number" },
    { name: "industry", label: "Industry" },
    { name: "preferred_installation_date", label: "Preferred installation date", type: "date" },
    { name: "request_status", label: "Request status", type: "select", options: ["new", "in_review", "scheduled", "in_progress", "completed", "rejected"] },
    { name: "assigned_deployment_manager", label: "Deployment manager" },
    { name: "additional_notes", label: "Additional notes", type: "textarea" },
    { name: "internal_notes", label: "Internal notes", type: "textarea" },
  ],
};

export const organizationsConfig: ResourceConfig = {
  key: "organizations",
  table: "organizations",
  title: "Organizations",
  singular: "Organization",
  description: "Every tenant on the platform, their plan and usage limits.",
  icon: "Landmark",
  statusField: "subscription_status",
  statusOptions: ["trial", "active", "past_due", "cancelled"],
  searchFields: ["name", "industry", "city", "country", "business_email"],
  columns: [
    { name: "name", label: "Organization", className: "font-medium" },
    { name: "industry", label: "Industry" },
    { name: "city", label: "City" },
    { name: "country", label: "Country" },
    { name: "number_of_employees", label: "Employees" },
    { name: "subscription_plan", label: "Plan", kind: "badge" },
    { name: "billing_cycle", label: "Cycle" },
    { name: "subscription_status", label: "Subscription", kind: "badge" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Organizations", value: rows.length, icon: "Landmark" },
    { label: "Active", value: countWhere(rows, (r) => r["subscription_status"] === "active"), icon: "CheckCircle2", tone: "success", filter: { field: "subscription_status", op: "eq", value: "active" } },
    { label: "On trial", value: countWhere(rows, (r) => r["subscription_status"] === "trial"), icon: "Clock", tone: "warning", filter: { field: "subscription_status", op: "eq", value: "trial" } },
    { label: "Past due", value: countWhere(rows, (r) => r["subscription_status"] === "past_due"), icon: "AlertTriangle", tone: "destructive", filter: { field: "subscription_status", op: "eq", value: "past_due" } },
  ],
  fields: [
    { name: "name", label: "Organization name", required: true, group: "Company" },
    { name: "slug", label: "Slug", group: "Company" },
    { name: "industry", label: "Industry", group: "Company" },
    { name: "business_email", label: "Business email", type: "email", group: "Company" },
    { name: "business_phone", label: "Business phone", group: "Company" },
    { name: "website", label: "Website", group: "Company" },
    { name: "address", label: "Address", group: "Company" },
    { name: "city", label: "City", group: "Company" },
    { name: "province_state", label: "Province / State", group: "Company" },
    { name: "country", label: "Country", group: "Company" },
    { name: "number_of_employees", label: "Employees", type: "number", group: "Company" },
    { name: "company_size", label: "Company size", type: "select", options: ["1-10", "11-50", "51-200", "201-1000", "1000+"], group: "Company" },
    { name: "gst_hst_number", label: "GST/HST number", group: "Company" },
    { name: "status", label: "Status", type: "select", options: ["active", "suspended", "inactive"], group: "Company" },

    { name: "subscription_plan", label: "Plan", type: "select", options: ["starter", "professional", "enterprise"], group: "Subscription" },
    { name: "subscription_status", label: "Subscription status", type: "select", options: ["trial", "active", "past_due", "cancelled"], group: "Subscription" },
    { name: "billing_cycle", label: "Billing cycle", type: "select", options: ["monthly", "annual"], group: "Subscription" },
    { name: "trial_start_date", label: "Trial start", type: "date", group: "Subscription" },
    { name: "trial_end_date", label: "Trial end", type: "date", group: "Subscription" },
    { name: "max_assets", label: "Max assets", type: "number", group: "Subscription" },
    { name: "max_users", label: "Max users", type: "number", group: "Subscription" },
    { name: "storage_limit_mb", label: "Storage limit (MB)", type: "number", group: "Subscription" },
  ],
};

export const invoicesConfig: ResourceConfig = {
  key: "invoices",
  table: "invoices",
  title: "Invoices",
  singular: "Invoice",
  description: "Subscription billing history across tenants.",
  icon: "Receipt",
  statusField: "status",
  statusOptions: ["draft", "open", "paid", "void", "unpaid"],
  searchFields: ["invoice_number", "organization_name", "plan"],
  columns: [
    { name: "invoice_number", label: "Invoice", kind: "mono" },
    { name: "organization_name", label: "Organization", className: "font-medium" },
    { name: "plan", label: "Plan", kind: "badge" },
    { name: "billing_cycle", label: "Cycle" },
    { name: "billing_period_start", label: "Period start", kind: "date" },
    { name: "billing_period_end", label: "Period end", kind: "date" },
    { name: "total", label: "Total", kind: "currency" },
    { name: "paid_date", label: "Paid", kind: "date" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  fields: [
    { name: "invoice_number", label: "Invoice number", required: true },
    { name: "organization_id", label: "Organization", required: true, ref: { table: "organizations", mirrorTo: "organization_name" } },
    { name: "plan", label: "Plan", type: "select", options: ["starter", "professional", "enterprise"] },
    { name: "billing_cycle", label: "Billing cycle", type: "select", options: ["monthly", "annual"] },
    { name: "billing_period_start", label: "Period start", type: "date" },
    { name: "billing_period_end", label: "Period end", type: "date" },
    { name: "subtotal", label: "Subtotal", type: "currency" },
    { name: "tax_amount", label: "Tax", type: "currency" },
    { name: "total", label: "Total", type: "currency" },
    { name: "currency", label: "Currency" },
    { name: "status", label: "Status", type: "select", options: ["draft", "open", "paid", "void", "unpaid"] },
    { name: "paid_date", label: "Paid date", type: "date" },
    { name: "pdf_url", label: "PDF URL" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const auditLogConfig: ResourceConfig = {
  key: "audit-log",
  table: "audit_logs",
  title: "Audit Log",
  singular: "Entry",
  description: "Immutable trail of everything that happened in your organization.",
  icon: "ScrollText",
  readOnly: true,
  statusField: "severity",
  statusOptions: ["info", "warning", "critical"],
  searchFields: ["action", "entity_type", "entity_name", "user_name", "user_email", "details"],
  columns: [
    { name: "created_at", label: "When", kind: "datetime" },
    { name: "action", label: "Action", className: "font-medium" },
    { name: "entity_type", label: "Entity" },
    { name: "entity_name", label: "Record" },
    { name: "user_name", label: "User" },
    { name: "user_email", label: "Email" },
    { name: "severity", label: "Severity", kind: "badge" },
    { name: "details", label: "Details", className: "max-w-[320px] truncate whitespace-normal" },
  ],
  fields: [],
};

export const warrantiesConfig: ResourceConfig = {
  key: "warranties",
  table: "assets",
  title: "Warranties",
  singular: "Warranty",
  description: "Warranty coverage windows and upcoming expiries across the estate.",
  icon: "ShieldCheck",
  orderBy: { column: "warranty_end", ascending: true },
  searchFields: ["name", "asset_tag", "vendor_name", "manufacturer"],
  columns: [
    { name: "name", label: "Asset", className: "font-medium" },
    { name: "asset_tag", label: "Tag", kind: "mono" },
    { name: "manufacturer", label: "Manufacturer" },
    { name: "vendor_name", label: "Vendor" },
    { name: "warranty_start", label: "Starts", kind: "date" },
    { name: "warranty_end", label: "Ends", kind: "date" },
    { name: "warranty_cost", label: "Cost", kind: "currency" },
    {
      name: "coverage",
      label: "Coverage",
      render: (r: Row) => {
        const end = r["warranty_end"];
        if (!end) return "—";
        if (isExpired(end)) return "Expired";
        if (isExpiring(end, 90)) return "Expiring soon";
        return "Covered";
      },
    },
  ],
  kpis: (rows) => [
    { label: "Under warranty", value: countWhere(rows, (r) => !!r["warranty_end"] && !isExpired(r["warranty_end"])), icon: "ShieldCheck", tone: "success", filter: [{ field: "warranty_end", op: "set" }, { field: "warranty_end", op: "next_days", value: 3650 }] },
    { label: "Expiring (90d)", value: countWhere(rows, (r) => isExpiring(r["warranty_end"], 90)), icon: "CalendarClock", tone: "warning", filter: { field: "warranty_end", op: "next_days", value: 90 } },
    { label: "Expired", value: countWhere(rows, (r) => isExpired(r["warranty_end"])), icon: "ShieldAlert", tone: "destructive", filter: { field: "warranty_end", op: "past" } },
    { label: "Warranty spend", value: currency(sum(rows, "warranty_cost")), icon: "DollarSign", filter: { field: "warranty_cost", op: "gt", value: 0 } },
  ],
  fields: [
    { name: "vendor_id", label: "Vendor", ref: { table: "vendors", mirrorTo: "vendor_name" } },
    { name: "warranty_start", label: "Warranty start", type: "date" },
    { name: "warranty_end", label: "Warranty end", type: "date" },
    { name: "warranty_cost", label: "Warranty cost", type: "currency" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};