import { countWhere, currency, sum, type ResourceConfig } from "./resource";

const STATUS = ["active", "inactive"];
export const PRIORITY = ["low", "medium", "high", "urgent"];
export const WO_STATUS = ["open", "assigned", "in_progress", "on_hold", "completed", "cancelled"];
export const WO_TYPES = [
  "corrective",
  "preventive",
  "predictive",
  "emergency",
  "inspection",
  "installation",
  "replacement",
  "calibration",
  "cleaning",
  "general_service",
];
export const SR_STATUS = ["new", "triaged", "assigned", "in_progress", "resolved", "closed", "rejected"];

export const sitesConfig: ResourceConfig = {
  key: "sites",
  table: "sites",
  title: "Sites",
  singular: "Site",
  description: "Campuses, sites, warehouses, yards and outdoor areas above your buildings.",
  icon: "MapPin",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "city", "address", "site_type"],
  columns: [
    { name: "name", label: "Site", className: "font-medium" },
    { name: "site_type", label: "Type", kind: "badge" },
    { name: "city", label: "City" },
    { name: "province_state", label: "Province / state" },
    { name: "gps_lat", label: "Latitude" },
    { name: "gps_lng", label: "Longitude" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Sites", value: rows.length, icon: "MapPin" },
    { label: "Active", value: countWhere(rows, (r) => r["status"] === "active"), icon: "CheckCircle2", tone: "success" },
    { label: "Geolocated", value: countWhere(rows, (r) => r["gps_lat"] !== null && r["gps_lat"] !== undefined), icon: "Globe" },
    { label: "Buildings", value: "See buildings", icon: "Building", to: "/buildings" },
  ],
  fields: [
    { name: "name", label: "Site name", required: true },
    { name: "site_type", label: "Site type", type: "select", options: ["site", "campus", "warehouse", "yard", "outdoor_area", "plant", "depot"] },
    { name: "address", label: "Address" },
    { name: "city", label: "City" },
    { name: "province_state", label: "Province / state" },
    { name: "country", label: "Country" },
    { name: "gps_lat", label: "GPS latitude", type: "number" },
    { name: "gps_lng", label: "GPS longitude", type: "number" },
    { name: "status", label: "Status", type: "select", options: STATUS },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const assetTypesConfig: ResourceConfig = {
  key: "asset-types",
  table: "asset_types",
  title: "Asset Types",
  singular: "Asset Type",
  description:
    "Define your own asset types — forklift, server, HVAC unit, streetlight, medical device — each with its own custom fields.",
  icon: "Shapes",
  statusField: "status",
  statusOptions: STATUS,
  searchFields: ["name", "module", "description"],
  columns: [
    { name: "name", label: "Type", className: "font-medium" },
    { name: "module", label: "Module", kind: "badge" },
    { name: "description", label: "Description" },
    { name: "default_maintenance_interval_days", label: "Default PM (days)" },
    { name: "status", label: "Status", kind: "badge" },
  ],
  kpis: (rows) => [
    { label: "Asset types", value: rows.length, icon: "Shapes" },
    { label: "With custom fields", value: countWhere(rows, (r) => Array.isArray(r["field_definitions"]) && (r["field_definitions"] as unknown[]).length > 0), icon: "ListChecks" },
    { label: "With default PM", value: countWhere(rows, (r) => !!r["default_maintenance_interval_days"]), icon: "CalendarClock" },
    { label: "Assets", value: "Open registry", icon: "Boxes", to: "/assets" },
  ],
  fields: [
    { name: "name", label: "Type name", required: true, help: "e.g. Forklift, Server, HVAC Unit, Streetlight" },
    { name: "icon", label: "Icon name", help: "Any Lucide icon name, e.g. Forklift, Server, Fan" },
    { name: "module", label: "Module", type: "select", options: ["asset_registry", "cmms", "fleet", "it_assets", "facilities", "medical", "inventory", "gis"] },
    { name: "default_maintenance_interval_days", label: "Default PM interval (days)", type: "number" },
    { name: "status", label: "Status", type: "select", options: STATUS },
    { name: "description", label: "Description", type: "textarea" },
  ],
};

export const serviceRequestsConfig: ResourceConfig = {
  key: "service-requests",
  table: "service_requests",
  title: "Service Requests",
  singular: "Service Request",
  description:
    "Intake from staff, residents, customers, technicians, email, API and IoT alerts — triaged and converted into work orders.",
  icon: "Inbox",
  statusField: "status",
  statusOptions: SR_STATUS,
  searchFields: ["title", "request_number", "requester_name", "asset_name", "building_name", "category"],
  columns: [
    { name: "request_number", label: "Ref", kind: "mono" },
    { name: "title", label: "Request", className: "font-medium" },
    { name: "category", label: "Category" },
    { name: "source", label: "Source", kind: "badge" },
    { name: "priority", label: "Priority", kind: "badge" },
    { name: "status", label: "Status", kind: "badge" },
    { name: "requester_name", label: "Requester" },
    { name: "asset_name", label: "Asset" },
    { name: "building_name", label: "Location" },
    { name: "sla_due_date", label: "SLA due", kind: "datetime" },
  ],
  kpis: (rows) => [
    { label: "Open requests", value: countWhere(rows, (r) => !["resolved", "closed", "rejected"].includes(String(r["status"]))), icon: "Inbox" },
    { label: "SLA breached", value: countWhere(rows, (r) => !!r["sla_due_date"] && new Date(String(r["sla_due_date"])).getTime() < Date.now() && !["resolved", "closed"].includes(String(r["status"]))), icon: "AlarmClock", tone: "destructive" },
    { label: "Urgent", value: countWhere(rows, (r) => r["priority"] === "urgent"), icon: "Flame", tone: "warning" },
    { label: "Work orders", value: "Open board", icon: "ClipboardList", to: "/work-orders" },
  ],
  fields: [
    { name: "title", label: "Request title", required: true, group: "Request" },
    { name: "request_number", label: "Reference", group: "Request" },
    { name: "category", label: "Category", group: "Request" },
    { name: "source", label: "Source", type: "select", options: ["portal", "employee", "customer", "resident", "technician", "manager", "email", "api", "iot_alert", "phone"], group: "Request" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY, group: "Request" },
    { name: "status", label: "Status", type: "select", options: SR_STATUS, group: "Request" },
    { name: "description", label: "Description", type: "textarea", group: "Request" },

    { name: "requester_name", label: "Requester", group: "Requester" },
    { name: "requester_email", label: "Requester email", type: "email", group: "Requester" },
    { name: "requester_phone", label: "Requester phone", group: "Requester" },
    { name: "department_id", label: "Department", ref: { table: "departments", mirrorTo: "department_name" }, group: "Requester" },

    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" }, group: "Location" },
    { name: "site_name", label: "Site", group: "Location" },
    { name: "building_name", label: "Building", group: "Location" },
    { name: "room_name", label: "Room", group: "Location" },
    { name: "location_notes", label: "Location notes", type: "textarea", group: "Location" },

    { name: "assigned_to_name", label: "Assigned to", group: "Handling" },
    { name: "sla_due_date", label: "SLA due", type: "datetime", group: "Handling" },
    { name: "resolution_notes", label: "Resolution notes", type: "textarea", group: "Handling" },
    { name: "photo_urls", label: "Photos", type: "files", accept: "image/*", folder: "service-requests", group: "Files" },
    { name: "document_urls", label: "Documents", type: "files", folder: "service-requests", group: "Files" },
  ],
};

export const workOrdersConfig: ResourceConfig = {
  key: "work-orders",
  table: "work_orders",
  title: "Work Orders",
  singular: "Work Order",
  description:
    "Corrective, preventive, predictive, emergency and inspection work with labour, parts, costs, checklists and sign-off.",
  icon: "ClipboardList",
  statusField: "status",
  statusOptions: WO_STATUS,
  searchFields: ["title", "work_order_number", "asset_name", "vehicle_name", "assigned_to_name", "contractor_name", "building_name"],
  columns: [
    { name: "work_order_number", label: "WO", kind: "mono" },
    { name: "title", label: "Work", className: "font-medium" },
    { name: "work_type", label: "Type", kind: "badge" },
    { name: "priority", label: "Priority", kind: "badge" },
    { name: "status", label: "Status", kind: "badge" },
    { name: "asset_name", label: "Asset" },
    { name: "assigned_to_name", label: "Assigned to" },
    { name: "scheduled_date", label: "Scheduled", kind: "date" },
    { name: "due_date", label: "Due", kind: "date" },
    { name: "total_cost", label: "Cost", kind: "currency" },
  ],
  kpis: (rows) => [
    { label: "Open work orders", value: countWhere(rows, (r) => !["completed", "cancelled"].includes(String(r["status"]))), icon: "ClipboardList" },
    { label: "Overdue", value: countWhere(rows, (r) => !!r["due_date"] && new Date(String(r["due_date"])).getTime() < Date.now() && !["completed", "cancelled"].includes(String(r["status"]))), icon: "AlarmClock", tone: "destructive" },
    { label: "Preventive share", value: `${rows.length ? Math.round((countWhere(rows, (r) => r["work_type"] === "preventive") / rows.length) * 100) : 0}%`, icon: "CalendarCheck", tone: "success" },
    { label: "Total cost", value: currency(sum(rows, "total_cost")), icon: "DollarSign" },
  ],
  fields: [
    { name: "title", label: "Work order title", required: true, group: "Work" },
    { name: "work_order_number", label: "WO number", group: "Work" },
    { name: "work_type", label: "Work type", type: "select", options: WO_TYPES, group: "Work" },
    { name: "trigger_type", label: "Triggered by", type: "select", options: ["manual", "service_request", "time", "meter", "mileage", "hours", "cycles", "sensor", "condition"], group: "Work" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY, group: "Work" },
    { name: "status", label: "Status", type: "select", options: WO_STATUS, group: "Work" },
    { name: "description", label: "Description", type: "textarea", group: "Work" },

    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" }, group: "Target" },
    { name: "vehicle_id", label: "Vehicle", ref: { table: "vehicles", mirrorTo: "vehicle_name" }, group: "Target" },
    { name: "site_name", label: "Site", group: "Target" },
    { name: "building_name", label: "Building", group: "Target" },
    { name: "room_name", label: "Room", group: "Target" },

    { name: "assigned_to_name", label: "Technician", group: "Resources" },
    { name: "assigned_to_email", label: "Technician email", type: "email", group: "Resources" },
    { name: "crew_name", label: "Crew", group: "Resources" },
    { name: "contractor_name", label: "Contractor", group: "Resources" },
    { name: "vendor_id", label: "Vendor", ref: { table: "vendors", mirrorTo: "vendor_name" }, group: "Resources" },

    { name: "scheduled_date", label: "Scheduled date", type: "date", group: "Schedule" },
    { name: "due_date", label: "Due date", type: "date", group: "Schedule" },
    { name: "completed_date", label: "Completed date", type: "date", group: "Schedule" },
    { name: "approval_status", label: "Approval", type: "select", options: ["not_required", "pending", "approved", "rejected"], group: "Schedule" },

    { name: "labour_hours", label: "Labour hours", type: "number", group: "Costs" },
    { name: "labour_cost", label: "Labour cost", type: "currency", group: "Costs" },
    { name: "parts_cost", label: "Parts cost", type: "currency", group: "Costs" },
    { name: "total_cost", label: "Total cost", type: "currency", group: "Costs" },
    { name: "mileage_km", label: "Mileage (km)", type: "number", group: "Costs" },
    { name: "meter_reading", label: "Meter reading", type: "number", group: "Costs" },
    { name: "downtime_hours", label: "Downtime (hours)", type: "number", group: "Costs" },
    { name: "parts_used", label: "Parts used", type: "textarea", group: "Costs" },

    { name: "signature_name", label: "Signed off by", group: "Closeout" },
    { name: "notes", label: "Notes", type: "textarea", group: "Closeout" },
    { name: "photo_urls", label: "Photos", type: "files", accept: "image/*", folder: "work-orders", group: "Files" },
    { name: "document_urls", label: "Documents", type: "files", folder: "work-orders", group: "Files" },
  ],
};

export const maintenancePlansConfig: ResourceConfig = {
  key: "maintenance-plans",
  table: "maintenance_plans",
  title: "Maintenance Plans",
  singular: "Plan",
  description:
    "Recurring triggers by calendar, mileage, operating hours, cycles, meter readings or sensor thresholds.",
  icon: "CalendarClock",
  statusField: "trigger_type",
  statusOptions: ["time", "mileage", "hours", "cycles", "meter", "sensor", "condition"],
  searchFields: ["name", "asset_name", "asset_type_name", "sensor_metric"],
  columns: [
    { name: "name", label: "Plan", className: "font-medium" },
    { name: "asset_name", label: "Asset" },
    { name: "work_type", label: "Work type", kind: "badge" },
    { name: "trigger_type", label: "Trigger", kind: "badge" },
    { name: "interval_days", label: "Every (days)" },
    { name: "interval_km", label: "Every (km)" },
    { name: "interval_hours", label: "Every (hrs)" },
    { name: "next_due_date", label: "Next due", kind: "date" },
    { name: "active", label: "Active", kind: "bool" },
  ],
  kpis: (rows) => [
    { label: "Plans", value: rows.length, icon: "CalendarClock" },
    { label: "Active", value: countWhere(rows, (r) => r["active"] === true), icon: "CheckCircle2", tone: "success" },
    { label: "Due in 30 days", value: countWhere(rows, (r) => !!r["next_due_date"] && new Date(String(r["next_due_date"])).getTime() < Date.now() + 30 * 86_400_000), icon: "AlarmClock", tone: "warning" },
    { label: "Sensor driven", value: countWhere(rows, (r) => r["trigger_type"] === "sensor"), icon: "Radio", to: "/iot" },
  ],
  fields: [
    { name: "name", label: "Plan name", required: true, group: "Plan" },
    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" }, group: "Plan" },
    { name: "asset_type_name", label: "Applies to asset type", group: "Plan" },
    { name: "work_type", label: "Work type", type: "select", options: WO_TYPES, group: "Plan" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY, group: "Plan" },
    { name: "assigned_to_name", label: "Default technician", group: "Plan" },
    { name: "active", label: "Active", type: "switch", group: "Plan" },
    { name: "description", label: "Description", type: "textarea", group: "Plan" },

    { name: "trigger_type", label: "Trigger type", type: "select", options: ["time", "mileage", "hours", "cycles", "meter", "sensor", "condition"], group: "Trigger" },
    { name: "interval_days", label: "Interval (days)", type: "number", group: "Trigger" },
    { name: "interval_km", label: "Interval (km)", type: "number", group: "Trigger" },
    { name: "interval_hours", label: "Interval (operating hours)", type: "number", group: "Trigger" },
    { name: "interval_cycles", label: "Interval (cycles)", type: "number", group: "Trigger" },
    { name: "meter_threshold", label: "Meter threshold", type: "number", group: "Trigger" },
    { name: "sensor_metric", label: "Sensor metric", group: "Trigger", help: "temperature, vibration, energy…" },
    { name: "sensor_threshold", label: "Sensor threshold", type: "number", group: "Trigger" },
    { name: "next_due_date", label: "Next due date", type: "date", group: "Trigger" },
  ],
};

export const inventoryConfig: ResourceConfig = {
  key: "inventory",
  table: "inventory_items",
  title: "Inventory & Parts",
  singular: "Item",
  description: "Parts, materials, supplies, consumables and tools with stock levels, reorder points and locations.",
  icon: "PackageSearch",
  statusField: "item_type",
  statusOptions: ["part", "material", "supply", "consumable", "tool"],
  searchFields: ["name", "sku", "category", "warehouse_name", "storage_location", "vendor_name"],
  columns: [
    { name: "sku", label: "SKU", kind: "mono" },
    { name: "name", label: "Item", className: "font-medium" },
    { name: "item_type", label: "Type", kind: "badge" },
    { name: "category", label: "Category" },
    { name: "quantity_on_hand", label: "On hand" },
    { name: "reorder_point", label: "Reorder at" },
    { name: "unit_cost", label: "Unit cost", kind: "currency" },
    { name: "warehouse_name", label: "Warehouse" },
    { name: "storage_location", label: "Location" },
    { name: "vendor_name", label: "Vendor" },
    { name: "expiry_date", label: "Expires", kind: "date" },
  ],
  kpis: (rows) => [
    { label: "Items tracked", value: rows.length, icon: "PackageSearch" },
    {
      label: "Inventory value",
      value: currency(
        rows.reduce(
          (t, r) => t + Number(r["quantity_on_hand"] ?? 0) * Number(r["unit_cost"] ?? 0),
          0,
        ),
      ),
      icon: "DollarSign",
    },
    {
      label: "Low stock",
      value: countWhere(rows, (r) => r["reorder_point"] != null && Number(r["quantity_on_hand"] ?? 0) <= Number(r["reorder_point"])),
      icon: "TrendingDown",
      tone: "destructive",
    },
    { label: "Out of stock", value: countWhere(rows, (r) => Number(r["quantity_on_hand"] ?? 0) <= 0), icon: "PackageX", tone: "warning" },
  ],
  fields: [
    { name: "name", label: "Item name", required: true, group: "Item" },
    { name: "sku", label: "SKU", group: "Item" },
    { name: "item_type", label: "Item type", type: "select", options: ["part", "material", "supply", "consumable", "tool"], group: "Item" },
    { name: "category", label: "Category", group: "Item" },
    { name: "manufacturer", label: "Manufacturer", group: "Item" },
    { name: "model", label: "Model", group: "Item" },
    { name: "unit", label: "Unit of measure", group: "Item" },
    { name: "description", label: "Description", type: "textarea", group: "Item" },

    { name: "quantity_on_hand", label: "Quantity on hand", type: "number", group: "Stock" },
    { name: "quantity_reserved", label: "Reserved", type: "number", group: "Stock" },
    { name: "reorder_point", label: "Reorder point", type: "number", group: "Stock" },
    { name: "min_stock", label: "Minimum stock", type: "number", group: "Stock" },
    { name: "max_stock", label: "Maximum stock", type: "number", group: "Stock" },
    { name: "unit_cost", label: "Unit cost", type: "currency", group: "Stock" },

    { name: "warehouse_name", label: "Warehouse", group: "Location" },
    { name: "storage_location", label: "Storage location", group: "Location" },
    { name: "site_name", label: "Site", group: "Location" },
    { name: "building_name", label: "Building", group: "Location" },
    { name: "serial_number", label: "Serial number", group: "Location" },
    { name: "lot_number", label: "Lot number", group: "Location" },
    { name: "expiry_date", label: "Expiry date", type: "date", group: "Location" },
    { name: "vendor_id", label: "Vendor", ref: { table: "vendors", mirrorTo: "vendor_name" }, group: "Location" },
    { name: "status", label: "Status", type: "select", options: STATUS, group: "Location" },
  ],
};

export const inventoryTxConfig: ResourceConfig = {
  key: "inventory-transactions",
  table: "inventory_transactions",
  title: "Stock Movements",
  singular: "Movement",
  description: "Receipts, issues to work orders, transfers, adjustments and returns.",
  icon: "ArrowLeftRight",
  statusField: "transaction_type",
  statusOptions: ["receipt", "issue", "transfer", "adjustment", "return"],
  searchFields: ["item_name", "work_order_number", "performed_by_name", "from_location", "to_location"],
  columns: [
    { name: "created_at", label: "When", kind: "datetime" },
    { name: "item_name", label: "Item", className: "font-medium" },
    { name: "transaction_type", label: "Type", kind: "badge" },
    { name: "quantity", label: "Qty" },
    { name: "unit_cost", label: "Unit cost", kind: "currency" },
    { name: "work_order_number", label: "Work order" },
    { name: "from_location", label: "From" },
    { name: "to_location", label: "To" },
    { name: "performed_by_name", label: "By" },
  ],
  fields: [
    { name: "item_id", label: "Item", ref: { table: "inventory_items", mirrorTo: "item_name" }, required: true },
    { name: "transaction_type", label: "Type", type: "select", options: ["receipt", "issue", "transfer", "adjustment", "return"] },
    { name: "quantity", label: "Quantity", type: "number" },
    { name: "unit_cost", label: "Unit cost", type: "currency" },
    { name: "work_order_id", label: "Work order", ref: { table: "work_orders", labelColumn: "title", mirrorTo: "work_order_number" } },
    { name: "from_location", label: "From location" },
    { name: "to_location", label: "To location" },
    { name: "performed_by_name", label: "Performed by" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};

export const iotDevicesConfig: ResourceConfig = {
  key: "iot",
  table: "iot_devices",
  title: "IoT & Sensors",
  singular: "Device",
  description:
    "Temperature, vibration, energy, GPS and industrial sensors linked to assets, with thresholds that can drive maintenance.",
  icon: "Radio",
  statusField: "device_status",
  statusOptions: ["connected", "not_connected", "configuration_required", "error", "syncing"],
  searchFields: ["name", "device_id", "metric", "asset_name", "building_name"],
  columns: [
    { name: "name", label: "Device", className: "font-medium" },
    { name: "device_type", label: "Type", kind: "badge" },
    { name: "metric", label: "Metric" },
    { name: "current_value", label: "Reading" },
    { name: "unit", label: "Unit" },
    { name: "min_threshold", label: "Min" },
    { name: "max_threshold", label: "Max" },
    { name: "device_status", label: "Connection", kind: "badge" },
    { name: "asset_name", label: "Asset" },
    { name: "building_name", label: "Location" },
    { name: "last_reading_at", label: "Last reading", kind: "datetime" },
  ],
  fields: [
    { name: "name", label: "Device name", required: true, group: "Device" },
    { name: "device_id", label: "Device ID", group: "Device" },
    { name: "device_type", label: "Device type", type: "select", options: ["sensor", "gateway", "meter", "gps_tracker", "controller", "camera"], group: "Device" },
    { name: "metric", label: "Metric", type: "select", options: ["temperature", "humidity", "vibration", "energy", "pressure", "flow", "gps", "runtime_hours", "door_state"], group: "Device" },
    { name: "unit", label: "Unit", group: "Device" },
    { name: "protocol", label: "Protocol", type: "select", options: ["mqtt", "rest", "modbus", "lorawan", "bacnet", "zigbee"], group: "Device" },
    { name: "manufacturer", label: "Manufacturer", group: "Device" },
    { name: "model", label: "Model", group: "Device" },
    { name: "device_status", label: "Connection status", type: "select", options: ["connected", "not_connected", "configuration_required", "error", "syncing"], group: "Device" },

    { name: "current_value", label: "Current value", type: "number", group: "Thresholds" },
    { name: "min_threshold", label: "Minimum threshold", type: "number", group: "Thresholds" },
    { name: "max_threshold", label: "Maximum threshold", type: "number", group: "Thresholds" },
    { name: "battery_level_pct", label: "Battery (%)", type: "number", group: "Thresholds" },
    { name: "last_reading_at", label: "Last reading", type: "datetime", group: "Thresholds" },

    { name: "asset_id", label: "Asset", ref: { table: "assets", mirrorTo: "asset_name" }, group: "Location" },
    { name: "site_name", label: "Site", group: "Location" },
    { name: "building_name", label: "Building", group: "Location" },
    { name: "room_name", label: "Room", group: "Location" },
    { name: "notes", label: "Notes", type: "textarea", group: "Location" },
  ],
};

export const automationConfig: ResourceConfig = {
  key: "automation",
  table: "automation_rules",
  title: "Automation",
  singular: "Rule",
  description: "No-code IF/THEN rules: warranty expiries, sensor thresholds, low stock and overdue work.",
  icon: "Workflow",
  statusField: "trigger_entity",
  statusOptions: ["asset", "work_order", "service_request", "inventory", "iot_device", "vehicle", "software"],
  searchFields: ["name", "trigger_event", "action_type", "description"],
  columns: [
    { name: "name", label: "Rule", className: "font-medium" },
    { name: "trigger_entity", label: "Entity", kind: "badge" },
    { name: "trigger_event", label: "When" },
    { name: "condition_field", label: "Field" },
    { name: "condition_operator", label: "Op" },
    { name: "condition_value", label: "Value" },
    { name: "action_type", label: "Then", kind: "badge" },
    { name: "active", label: "Active", kind: "bool" },
    { name: "last_run_at", label: "Last run", kind: "datetime" },
  ],
  kpis: (rows) => [
    { label: "Rules", value: rows.length, icon: "Workflow" },
    { label: "Active", value: countWhere(rows, (r) => r["active"] === true), icon: "Zap", tone: "success" },
    { label: "Create work orders", value: countWhere(rows, (r) => r["action_type"] === "create_work_order"), icon: "ClipboardList", to: "/work-orders" },
    { label: "Notify only", value: countWhere(rows, (r) => r["action_type"] === "notify"), icon: "BellRing" },
  ],
  fields: [
    { name: "name", label: "Rule name", required: true, group: "Rule" },
    { name: "active", label: "Active", type: "switch", group: "Rule" },
    { name: "description", label: "Description", type: "textarea", group: "Rule" },

    { name: "trigger_entity", label: "Entity", type: "select", options: ["asset", "work_order", "service_request", "inventory", "iot_device", "vehicle", "software"], group: "If" },
    { name: "trigger_event", label: "Event", type: "select", options: ["warranty_expiring", "threshold_breached", "below_reorder_point", "overdue", "status_changed", "created", "licence_expiring", "meter_reached"], group: "If" },
    { name: "condition_field", label: "Field", group: "If" },
    { name: "condition_operator", label: "Operator", type: "select", options: ["lt", "lte", "eq", "gte", "gt", "neq", "contains"], group: "If" },
    { name: "condition_value", label: "Value", group: "If" },

    { name: "action_type", label: "Action", type: "select", options: ["notify", "create_work_order", "create_service_request", "assign", "create_purchase_request", "webhook"], group: "Then" },
  ],
};

export const documentsConfig: ResourceConfig = {
  key: "documents",
  table: "documents",
  title: "Documents",
  singular: "Document",
  description: "Contracts, manuals, receipts, warranties, inspection reports and photos attached to any record.",
  icon: "FolderOpen",
  statusField: "doc_type",
  statusOptions: ["document", "contract", "manual", "receipt", "warranty", "inspection", "photo", "video", "certificate"],
  searchFields: ["title", "entity_name", "entity_type", "file_name"],
  columns: [
    { name: "title", label: "Document", className: "font-medium" },
    { name: "doc_type", label: "Type", kind: "badge" },
    { name: "entity_type", label: "Attached to", kind: "badge" },
    { name: "entity_name", label: "Record" },
    { name: "uploaded_by_name", label: "Uploaded by" },
    { name: "created_at", label: "Uploaded", kind: "datetime" },
  ],
  fields: [
    { name: "title", label: "Title", required: true },
    { name: "doc_type", label: "Document type", type: "select", options: ["document", "contract", "manual", "receipt", "warranty", "inspection", "photo", "video", "certificate"] },
    { name: "entity_type", label: "Attached to", type: "select", options: ["asset", "work_order", "service_request", "vendor", "vehicle", "building", "person", "contract", "inventory_item"] },
    { name: "entity_name", label: "Record name" },
    { name: "file_url", label: "File", type: "files", folder: "documents", required: true, help: "Upload one file; the first upload is stored as the document." },
    { name: "uploaded_by_name", label: "Uploaded by" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
};