/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedAssetCategoriesRouteImport } from './routes/_authenticated/asset-categories'
import { Route as AuthenticatedAssetTypesRouteImport } from './routes/_authenticated/asset-types'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedBuildingsRouteImport } from './routes/_authenticated/buildings'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFloorPlanRouteImport } from './routes/_authenticated/floor-plan'
import { Route as AuthenticatedGeofencesRouteImport } from './routes/_authenticated/geofences'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedIotRouteImport } from './routes/_authenticated/iot'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMaintenanceCalendarRouteImport } from './routes/_authenticated/maintenance-calendar'
import { Route as AuthenticatedMaintenancePlansRouteImport } from './routes/_authenticated/maintenance-plans'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedPeopleSearchRouteImport } from './routes/_authenticated/people-search'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedServiceRequestsRouteImport } from './routes/_authenticated/service-requests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSoftwareRouteImport } from './routes/_authenticated/software'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedTechnicianPortalRouteImport } from './routes/_authenticated/technician-portal'
import { Route as AuthenticatedUsersManagementRouteImport } from './routes/_authenticated/users-management'
import { Route as AuthenticatedVehicleServiceRouteImport } from './routes/_authenticated/vehicle-service'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedWarrantiesRouteImport } from './routes/_authenticated/warranties'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets_.$id'
import { Route as AuthenticatedRfidAlertsRouteImport } from './routes/_authenticated/rfid.alerts'
import { Route as AuthenticatedRfidAssetsRouteImport } from './routes/_authenticated/rfid.assets'
import { Route as AuthenticatedRfidDashboardRouteImport } from './routes/_authenticated/rfid.dashboard'
import { Route as AuthenticatedRfidGatewaysRouteImport } from './routes/_authenticated/rfid.gateways'
import { Route as AuthenticatedRfidLiveRouteImport } from './routes/_authenticated/rfid.live'
import { Route as AuthenticatedRfidMovementRouteImport } from './routes/_authenticated/rfid.movement'
import { Route as AuthenticatedRfidOnboardingRouteImport } from './routes/_authenticated/rfid.onboarding'
import { Route as AuthenticatedRfidReadersRouteImport } from './routes/_authenticated/rfid.readers'
import { Route as AuthenticatedRfidReportsRouteImport } from './routes/_authenticated/rfid.reports'
import { Route as AuthenticatedRfidSettingsRouteImport } from './routes/_authenticated/rfid.settings'
import { Route as AuthenticatedRfidZonesRouteImport } from './routes/_authenticated/rfid.zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetCategoriesRoute =
  AuthenticatedAssetCategoriesRouteImport.update({
    id: '/asset-categories',
    path: '/asset-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetTypesRoute = AuthenticatedAssetTypesRouteImport.update({
  id: '/asset-types',
  path: '/asset-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingsRoute = AuthenticatedBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFloorPlanRoute = AuthenticatedFloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeofencesRoute = AuthenticatedGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIotRoute = AuthenticatedIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceCalendarRoute =
  AuthenticatedMaintenanceCalendarRouteImport.update({
    id: '/maintenance-calendar',
    path: '/maintenance-calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenancePlansRoute =
  AuthenticatedMaintenancePlansRouteImport.update({
    id: '/maintenance-plans',
    path: '/maintenance-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleSearchRoute =
  AuthenticatedPeopleSearchRouteImport.update({
    id: '/people-search',
    path: '/people-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceRequestsRoute =
  AuthenticatedServiceRequestsRouteImport.update({
    id: '/service-requests',
    path: '/service-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoftwareRoute = AuthenticatedSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechnicianPortalRoute =
  AuthenticatedTechnicianPortalRouteImport.update({
    id: '/technician-portal',
    path: '/technician-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersManagementRoute =
  AuthenticatedUsersManagementRouteImport.update({
    id: '/users-management',
    path: '/users-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehicleServiceRoute =
  AuthenticatedVehicleServiceRouteImport.update({
    id: '/vehicle-service',
    path: '/vehicle-service',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarrantiesRoute = AuthenticatedWarrantiesRouteImport.update({
  id: '/warranties',
  path: '/warranties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets_/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfidAlertsRoute = AuthenticatedRfidAlertsRouteImport.update({
  id: '/rfid/alerts',
  path: '/rfid/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfidAssetsRoute = AuthenticatedRfidAssetsRouteImport.update({
  id: '/rfid/assets',
  path: '/rfid/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfidDashboardRoute =
  AuthenticatedRfidDashboardRouteImport.update({
    id: '/rfid/dashboard',
    path: '/rfid/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidGatewaysRoute =
  AuthenticatedRfidGatewaysRouteImport.update({
    id: '/rfid/gateways',
    path: '/rfid/gateways',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidLiveRoute = AuthenticatedRfidLiveRouteImport.update({
  id: '/rfid/live',
  path: '/rfid/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfidMovementRoute =
  AuthenticatedRfidMovementRouteImport.update({
    id: '/rfid/movement',
    path: '/rfid/movement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidOnboardingRoute =
  AuthenticatedRfidOnboardingRouteImport.update({
    id: '/rfid/onboarding',
    path: '/rfid/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidReadersRoute =
  AuthenticatedRfidReadersRouteImport.update({
    id: '/rfid/readers',
    path: '/rfid/readers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidReportsRoute =
  AuthenticatedRfidReportsRouteImport.update({
    id: '/rfid/reports',
    path: '/rfid/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidSettingsRoute =
  AuthenticatedRfidSettingsRouteImport.update({
    id: '/rfid/settings',
    path: '/rfid/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidZonesRoute = AuthenticatedRfidZonesRouteImport.update({
  id: '/rfid/zones',
  path: '/rfid/zones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/asset-categories': typeof AuthenticatedAssetCategoriesRoute
  '/asset-types': typeof AuthenticatedAssetTypesRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/floor-plan': typeof AuthenticatedFloorPlanRoute
  '/geofences': typeof AuthenticatedGeofencesRoute
  '/import': typeof AuthenticatedImportRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/iot': typeof AuthenticatedIotRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/maintenance-calendar': typeof AuthenticatedMaintenanceCalendarRoute
  '/maintenance-plans': typeof AuthenticatedMaintenancePlansRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/people-search': typeof AuthenticatedPeopleSearchRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/service-requests': typeof AuthenticatedServiceRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/software': typeof AuthenticatedSoftwareRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/technician-portal': typeof AuthenticatedTechnicianPortalRoute
  '/users-management': typeof AuthenticatedUsersManagementRoute
  '/vehicle-service': typeof AuthenticatedVehicleServiceRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/warranties': typeof AuthenticatedWarrantiesRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/rfid/alerts': typeof AuthenticatedRfidAlertsRoute
  '/rfid/assets': typeof AuthenticatedRfidAssetsRoute
  '/rfid/dashboard': typeof AuthenticatedRfidDashboardRoute
  '/rfid/gateways': typeof AuthenticatedRfidGatewaysRoute
  '/rfid/live': typeof AuthenticatedRfidLiveRoute
  '/rfid/movement': typeof AuthenticatedRfidMovementRoute
  '/rfid/onboarding': typeof AuthenticatedRfidOnboardingRoute
  '/rfid/readers': typeof AuthenticatedRfidReadersRoute
  '/rfid/reports': typeof AuthenticatedRfidReportsRoute
  '/rfid/settings': typeof AuthenticatedRfidSettingsRoute
  '/rfid/zones': typeof AuthenticatedRfidZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/asset-categories': typeof AuthenticatedAssetCategoriesRoute
  '/asset-types': typeof AuthenticatedAssetTypesRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/floor-plan': typeof AuthenticatedFloorPlanRoute
  '/geofences': typeof AuthenticatedGeofencesRoute
  '/import': typeof AuthenticatedImportRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/iot': typeof AuthenticatedIotRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/maintenance-calendar': typeof AuthenticatedMaintenanceCalendarRoute
  '/maintenance-plans': typeof AuthenticatedMaintenancePlansRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/people-search': typeof AuthenticatedPeopleSearchRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/service-requests': typeof AuthenticatedServiceRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/software': typeof AuthenticatedSoftwareRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/technician-portal': typeof AuthenticatedTechnicianPortalRoute
  '/users-management': typeof AuthenticatedUsersManagementRoute
  '/vehicle-service': typeof AuthenticatedVehicleServiceRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/warranties': typeof AuthenticatedWarrantiesRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/rfid/alerts': typeof AuthenticatedRfidAlertsRoute
  '/rfid/assets': typeof AuthenticatedRfidAssetsRoute
  '/rfid/dashboard': typeof AuthenticatedRfidDashboardRoute
  '/rfid/gateways': typeof AuthenticatedRfidGatewaysRoute
  '/rfid/live': typeof AuthenticatedRfidLiveRoute
  '/rfid/movement': typeof AuthenticatedRfidMovementRoute
  '/rfid/onboarding': typeof AuthenticatedRfidOnboardingRoute
  '/rfid/readers': typeof AuthenticatedRfidReadersRoute
  '/rfid/reports': typeof AuthenticatedRfidReportsRoute
  '/rfid/settings': typeof AuthenticatedRfidSettingsRoute
  '/rfid/zones': typeof AuthenticatedRfidZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/asset-categories': typeof AuthenticatedAssetCategoriesRoute
  '/_authenticated/asset-types': typeof AuthenticatedAssetTypesRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/buildings': typeof AuthenticatedBuildingsRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/floor-plan': typeof AuthenticatedFloorPlanRoute
  '/_authenticated/geofences': typeof AuthenticatedGeofencesRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/iot': typeof AuthenticatedIotRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/maintenance-calendar': typeof AuthenticatedMaintenanceCalendarRoute
  '/_authenticated/maintenance-plans': typeof AuthenticatedMaintenancePlansRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/people-search': typeof AuthenticatedPeopleSearchRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/service-requests': typeof AuthenticatedServiceRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/software': typeof AuthenticatedSoftwareRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/technician-portal': typeof AuthenticatedTechnicianPortalRoute
  '/_authenticated/users-management': typeof AuthenticatedUsersManagementRoute
  '/_authenticated/vehicle-service': typeof AuthenticatedVehicleServiceRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/warranties': typeof AuthenticatedWarrantiesRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/_authenticated/assets_/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/rfid/alerts': typeof AuthenticatedRfidAlertsRoute
  '/_authenticated/rfid/assets': typeof AuthenticatedRfidAssetsRoute
  '/_authenticated/rfid/dashboard': typeof AuthenticatedRfidDashboardRoute
  '/_authenticated/rfid/gateways': typeof AuthenticatedRfidGatewaysRoute
  '/_authenticated/rfid/live': typeof AuthenticatedRfidLiveRoute
  '/_authenticated/rfid/movement': typeof AuthenticatedRfidMovementRoute
  '/_authenticated/rfid/onboarding': typeof AuthenticatedRfidOnboardingRoute
  '/_authenticated/rfid/readers': typeof AuthenticatedRfidReadersRoute
  '/_authenticated/rfid/reports': typeof AuthenticatedRfidReportsRoute
  '/_authenticated/rfid/settings': typeof AuthenticatedRfidSettingsRoute
  '/_authenticated/rfid/zones': typeof AuthenticatedRfidZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-assistant'
    | '/api-docs'
    | '/asset-categories'
    | '/asset-types'
    | '/assets'
    | '/assignments'
    | '/audit-log'
    | '/automation'
    | '/buildings'
    | '/departments'
    | '/distribution'
    | '/documents'
    | '/floor-plan'
    | '/geofences'
    | '/import'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/iot'
    | '/maintenance'
    | '/maintenance-calendar'
    | '/maintenance-plans'
    | '/modules'
    | '/network'
    | '/organizations'
    | '/people-search'
    | '/reports'
    | '/rooms'
    | '/service-requests'
    | '/settings'
    | '/sites'
    | '/software'
    | '/super-admin'
    | '/technician-portal'
    | '/users-management'
    | '/vehicle-service'
    | '/vehicles'
    | '/vendors'
    | '/warranties'
    | '/work-orders'
    | '/assets/$id'
    | '/rfid/alerts'
    | '/rfid/assets'
    | '/rfid/dashboard'
    | '/rfid/gateways'
    | '/rfid/live'
    | '/rfid/movement'
    | '/rfid/onboarding'
    | '/rfid/readers'
    | '/rfid/reports'
    | '/rfid/settings'
    | '/rfid/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-assistant'
    | '/api-docs'
    | '/asset-categories'
    | '/asset-types'
    | '/assets'
    | '/assignments'
    | '/audit-log'
    | '/automation'
    | '/buildings'
    | '/departments'
    | '/distribution'
    | '/documents'
    | '/floor-plan'
    | '/geofences'
    | '/import'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/iot'
    | '/maintenance'
    | '/maintenance-calendar'
    | '/maintenance-plans'
    | '/modules'
    | '/network'
    | '/organizations'
    | '/people-search'
    | '/reports'
    | '/rooms'
    | '/service-requests'
    | '/settings'
    | '/sites'
    | '/software'
    | '/super-admin'
    | '/technician-portal'
    | '/users-management'
    | '/vehicle-service'
    | '/vehicles'
    | '/vendors'
    | '/warranties'
    | '/work-orders'
    | '/assets/$id'
    | '/rfid/alerts'
    | '/rfid/assets'
    | '/rfid/dashboard'
    | '/rfid/gateways'
    | '/rfid/live'
    | '/rfid/movement'
    | '/rfid/onboarding'
    | '/rfid/readers'
    | '/rfid/reports'
    | '/rfid/settings'
    | '/rfid/zones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/api-docs'
    | '/_authenticated/asset-categories'
    | '/_authenticated/asset-types'
    | '/_authenticated/assets'
    | '/_authenticated/assignments'
    | '/_authenticated/audit-log'
    | '/_authenticated/automation'
    | '/_authenticated/buildings'
    | '/_authenticated/departments'
    | '/_authenticated/distribution'
    | '/_authenticated/documents'
    | '/_authenticated/floor-plan'
    | '/_authenticated/geofences'
    | '/_authenticated/import'
    | '/_authenticated/integrations'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/iot'
    | '/_authenticated/maintenance'
    | '/_authenticated/maintenance-calendar'
    | '/_authenticated/maintenance-plans'
    | '/_authenticated/modules'
    | '/_authenticated/network'
    | '/_authenticated/organizations'
    | '/_authenticated/people-search'
    | '/_authenticated/reports'
    | '/_authenticated/rooms'
    | '/_authenticated/service-requests'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/_authenticated/software'
    | '/_authenticated/super-admin'
    | '/_authenticated/technician-portal'
    | '/_authenticated/users-management'
    | '/_authenticated/vehicle-service'
    | '/_authenticated/vehicles'
    | '/_authenticated/vendors'
    | '/_authenticated/warranties'
    | '/_authenticated/work-orders'
    | '/_authenticated/assets_/$id'
    | '/_authenticated/rfid/alerts'
    | '/_authenticated/rfid/assets'
    | '/_authenticated/rfid/dashboard'
    | '/_authenticated/rfid/gateways'
    | '/_authenticated/rfid/live'
    | '/_authenticated/rfid/movement'
    | '/_authenticated/rfid/onboarding'
    | '/_authenticated/rfid/readers'
    | '/_authenticated/rfid/reports'
    | '/_authenticated/rfid/settings'
    | '/_authenticated/rfid/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asset-categories': {
      id: '/_authenticated/asset-categories'
      path: '/asset-categories'
      fullPath: '/asset-categories'
      preLoaderRoute: typeof AuthenticatedAssetCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asset-types': {
      id: '/_authenticated/asset-types'
      path: '/asset-types'
      fullPath: '/asset-types'
      preLoaderRoute: typeof AuthenticatedAssetTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buildings': {
      id: '/_authenticated/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedBuildingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/floor-plan': {
      id: '/_authenticated/floor-plan'
      path: '/floor-plan'
      fullPath: '/floor-plan'
      preLoaderRoute: typeof AuthenticatedFloorPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geofences': {
      id: '/_authenticated/geofences'
      path: '/geofences'
      fullPath: '/geofences'
      preLoaderRoute: typeof AuthenticatedGeofencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iot': {
      id: '/_authenticated/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof AuthenticatedIotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance-calendar': {
      id: '/_authenticated/maintenance-calendar'
      path: '/maintenance-calendar'
      fullPath: '/maintenance-calendar'
      preLoaderRoute: typeof AuthenticatedMaintenanceCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance-plans': {
      id: '/_authenticated/maintenance-plans'
      path: '/maintenance-plans'
      fullPath: '/maintenance-plans'
      preLoaderRoute: typeof AuthenticatedMaintenancePlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people-search': {
      id: '/_authenticated/people-search'
      path: '/people-search'
      fullPath: '/people-search'
      preLoaderRoute: typeof AuthenticatedPeopleSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-requests': {
      id: '/_authenticated/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof AuthenticatedServiceRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/software': {
      id: '/_authenticated/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof AuthenticatedSoftwareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technician-portal': {
      id: '/_authenticated/technician-portal'
      path: '/technician-portal'
      fullPath: '/technician-portal'
      preLoaderRoute: typeof AuthenticatedTechnicianPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users-management': {
      id: '/_authenticated/users-management'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof AuthenticatedUsersManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicle-service': {
      id: '/_authenticated/vehicle-service'
      path: '/vehicle-service'
      fullPath: '/vehicle-service'
      preLoaderRoute: typeof AuthenticatedVehicleServiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warranties': {
      id: '/_authenticated/warranties'
      path: '/warranties'
      fullPath: '/warranties'
      preLoaderRoute: typeof AuthenticatedWarrantiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets_/$id': {
      id: '/_authenticated/assets_/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/alerts': {
      id: '/_authenticated/rfid/alerts'
      path: '/rfid/alerts'
      fullPath: '/rfid/alerts'
      preLoaderRoute: typeof AuthenticatedRfidAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/assets': {
      id: '/_authenticated/rfid/assets'
      path: '/rfid/assets'
      fullPath: '/rfid/assets'
      preLoaderRoute: typeof AuthenticatedRfidAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/dashboard': {
      id: '/_authenticated/rfid/dashboard'
      path: '/rfid/dashboard'
      fullPath: '/rfid/dashboard'
      preLoaderRoute: typeof AuthenticatedRfidDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/gateways': {
      id: '/_authenticated/rfid/gateways'
      path: '/rfid/gateways'
      fullPath: '/rfid/gateways'
      preLoaderRoute: typeof AuthenticatedRfidGatewaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/live': {
      id: '/_authenticated/rfid/live'
      path: '/rfid/live'
      fullPath: '/rfid/live'
      preLoaderRoute: typeof AuthenticatedRfidLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/movement': {
      id: '/_authenticated/rfid/movement'
      path: '/rfid/movement'
      fullPath: '/rfid/movement'
      preLoaderRoute: typeof AuthenticatedRfidMovementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/onboarding': {
      id: '/_authenticated/rfid/onboarding'
      path: '/rfid/onboarding'
      fullPath: '/rfid/onboarding'
      preLoaderRoute: typeof AuthenticatedRfidOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/readers': {
      id: '/_authenticated/rfid/readers'
      path: '/rfid/readers'
      fullPath: '/rfid/readers'
      preLoaderRoute: typeof AuthenticatedRfidReadersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/reports': {
      id: '/_authenticated/rfid/reports'
      path: '/rfid/reports'
      fullPath: '/rfid/reports'
      preLoaderRoute: typeof AuthenticatedRfidReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/settings': {
      id: '/_authenticated/rfid/settings'
      path: '/rfid/settings'
      fullPath: '/rfid/settings'
      preLoaderRoute: typeof AuthenticatedRfidSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid/zones': {
      id: '/_authenticated/rfid/zones'
      path: '/rfid/zones'
      fullPath: '/rfid/zones'
      preLoaderRoute: typeof AuthenticatedRfidZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedAssetCategoriesRoute: typeof AuthenticatedAssetCategoriesRoute
  AuthenticatedAssetTypesRoute: typeof AuthenticatedAssetTypesRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedBuildingsRoute: typeof AuthenticatedBuildingsRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFloorPlanRoute: typeof AuthenticatedFloorPlanRoute
  AuthenticatedGeofencesRoute: typeof AuthenticatedGeofencesRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedIotRoute: typeof AuthenticatedIotRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMaintenanceCalendarRoute: typeof AuthenticatedMaintenanceCalendarRoute
  AuthenticatedMaintenancePlansRoute: typeof AuthenticatedMaintenancePlansRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedPeopleSearchRoute: typeof AuthenticatedPeopleSearchRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedServiceRequestsRoute: typeof AuthenticatedServiceRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedSoftwareRoute: typeof AuthenticatedSoftwareRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedTechnicianPortalRoute: typeof AuthenticatedTechnicianPortalRoute
  AuthenticatedUsersManagementRoute: typeof AuthenticatedUsersManagementRoute
  AuthenticatedVehicleServiceRoute: typeof AuthenticatedVehicleServiceRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWarrantiesRoute: typeof AuthenticatedWarrantiesRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedRfidAlertsRoute: typeof AuthenticatedRfidAlertsRoute
  AuthenticatedRfidAssetsRoute: typeof AuthenticatedRfidAssetsRoute
  AuthenticatedRfidDashboardRoute: typeof AuthenticatedRfidDashboardRoute
  AuthenticatedRfidGatewaysRoute: typeof AuthenticatedRfidGatewaysRoute
  AuthenticatedRfidLiveRoute: typeof AuthenticatedRfidLiveRoute
  AuthenticatedRfidMovementRoute: typeof AuthenticatedRfidMovementRoute
  AuthenticatedRfidOnboardingRoute: typeof AuthenticatedRfidOnboardingRoute
  AuthenticatedRfidReadersRoute: typeof AuthenticatedRfidReadersRoute
  AuthenticatedRfidReportsRoute: typeof AuthenticatedRfidReportsRoute
  AuthenticatedRfidSettingsRoute: typeof AuthenticatedRfidSettingsRoute
  AuthenticatedRfidZonesRoute: typeof AuthenticatedRfidZonesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedAssetCategoriesRoute: AuthenticatedAssetCategoriesRoute,
  AuthenticatedAssetTypesRoute: AuthenticatedAssetTypesRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedBuildingsRoute: AuthenticatedBuildingsRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFloorPlanRoute: AuthenticatedFloorPlanRoute,
  AuthenticatedGeofencesRoute: AuthenticatedGeofencesRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedIotRoute: AuthenticatedIotRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMaintenanceCalendarRoute: AuthenticatedMaintenanceCalendarRoute,
  AuthenticatedMaintenancePlansRoute: AuthenticatedMaintenancePlansRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedPeopleSearchRoute: AuthenticatedPeopleSearchRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedServiceRequestsRoute: AuthenticatedServiceRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedSoftwareRoute: AuthenticatedSoftwareRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedTechnicianPortalRoute: AuthenticatedTechnicianPortalRoute,
  AuthenticatedUsersManagementRoute: AuthenticatedUsersManagementRoute,
  AuthenticatedVehicleServiceRoute: AuthenticatedVehicleServiceRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWarrantiesRoute: AuthenticatedWarrantiesRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedRfidAlertsRoute: AuthenticatedRfidAlertsRoute,
  AuthenticatedRfidAssetsRoute: AuthenticatedRfidAssetsRoute,
  AuthenticatedRfidDashboardRoute: AuthenticatedRfidDashboardRoute,
  AuthenticatedRfidGatewaysRoute: AuthenticatedRfidGatewaysRoute,
  AuthenticatedRfidLiveRoute: AuthenticatedRfidLiveRoute,
  AuthenticatedRfidMovementRoute: AuthenticatedRfidMovementRoute,
  AuthenticatedRfidOnboardingRoute: AuthenticatedRfidOnboardingRoute,
  AuthenticatedRfidReadersRoute: AuthenticatedRfidReadersRoute,
  AuthenticatedRfidReportsRoute: AuthenticatedRfidReportsRoute,
  AuthenticatedRfidSettingsRoute: AuthenticatedRfidSettingsRoute,
  AuthenticatedRfidZonesRoute: AuthenticatedRfidZonesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
